language: node_js
node_js:
- "node"
#- "8.12"

cache:
  directories:
    - node_modules
  yarn: true

install:
- yarn install --ignore-scripts

script:
- yarn less:lint
- yarn test
- yarn build

after_script:
  - chmod a+x ./_scripts/bump.sh
  - ./_scripts/bump.sh
