language: node_js
node_js:
- "8.12"

before_install:
- export TZ=Europe/Oslo

install:
- yarn install

before_script:
- yarn less:lint

script:
- yarn build

before_deploy:
# Set up git user name and tag this commit
# bytte epost til nav
- git config --local user.name "navikt"
- git config --local user.email "petterruud@gmail.com"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  - provider: releases
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master
    keep-history: true
    local-dir: "target"
