language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
  yarn: true

addons:
  sonarcloud:
    organization: "navit"
    token:
      secure: VkvpAqpIo3uo44AShIjR6aDMs05/E2glZgtqm/tW1/J5HGM1m/UZB4i5hlN7Oipz+gPXC7bNsDhJVzWto8FmYv+NhLoaSWoKKsxr/xuCG8T97p8MMbtnNPpsj1XLfYPhnqP+NLvOk4zS65k8BbWGWuFp7JQdg2C/x2B895u4k6C5WXUkT6HFLfn2IjKLQD9FJmWb1wvhA4d5uLhaRXAxT8SdKplRYt21XfdxxBgjH76r1SxOzr27RQDCL0uhe5ass8Wzo4gTp0+xXC0P/UKtC6Jce3EXmJUIWy+US7lotg+o1n89vMs2NRsaqf/UWHJiL6N+PVSmL8zozI0v5DAnaWT4HopHQB63sflAR+/XULbxi0E3uaGclfjL/j+JtlJNYnlM0CLvqiRU/5N7CGIOpTcbtqEuwyU2h6HkXPRtjGGlGkO7Qzm21cSJbGPMHQzXxEuuF1Z6JGRQ0XAp+wl9fewQOtgWCFSCZAUhAibRTkkZpnLqZSM+2c4XpsPWtrAHef6w735tJ7z+FkFmtk9boLFFbLFKX+dA6renlK8wgKia9DDBCRWSKbmb53bVMbwwIP1wVjQpYiLIkmw6VEL/InW2/+0JLP4BKAFshK+21FeSJxrGTRNukuwfKl5xHuV9bnnCyOyZgmoeepdmoSn5xIkotZtJSKJ4E7sgTLhDD2Y=


install:
- yarn install --ignore-scripts --no-progress

script:
- yarn less:lint
- yarn test
- yarn build
- chmod a+x ./travis/sonar.sh
- "./travis/sonar.sh"
- git config user.name team-foreldrepenger[bot]
- git config user.email team-foreldrepenger[bot]@users.noreply.github.com


after_script:
- chmod a+x ./travis/push-tag.sh
- "./travis/push-tag.sh"

before_install:
- openssl aes-256-cbc -K $encrypted_95f19733e3f4_key -iv $encrypted_95f19733e3f4_iv
  -in travis/private.enc -out travis/private.pem -d
- git clone https://github.com/navikt/github-apps-support.git
- export PATH=`pwd`/github-apps-support/bin:$PATH
- export INSTALLATION_TOKEN=$(generate-installation-token.sh `generate-jwt.sh ./travis/private.pem $GITHUB_APP_ID`)

env:
  global:
    secure: KNflK1REvC9ar1sePdW/BkWQxtBzR2QuWoWyVHfcDKRswVUd5nqZ9g/hi/OX6wO2b49yMUp0W6JH8NVnBhNIS3r7T1LDZmwEikLG/agdkMeyBUynGVYOvLgk2C9sIaenfUTquMH0eSYO0VdaI/wnLhKP74L2ZcxcNV5UKe7z+fCPoqtvnzPVZU1fqZwK73bTeqrHTlm93pg5XePj9bLPpF7JjlgAap/G3vly6/sGET5zIE3zE7Kzu6bLjjWlqBaeTYskezGPR9dPobza444j/VpLNLBHU6NvI1yUO37PdsEtwP7wYEvjMpUHW5J86RaQA59noMy6EiSj9KhMgUNJ/PSODyl+sivnZeac0u6IDahape94aXAdcdkTuiQ1lvkkEqcsliw/nRQ+3g8McYzryjl8LyvAlMHVneMvKE0q9OKFgRKftEJLcvXPzmOtiL/C4j5qYZFMaftt5ByR7V+lrOgFklphGqtpu1+VKtH7zetSFUQZRhoPNpW3osMX2i/hV51sAiLT+2J2WDg0T2zbJSu5UYekFdhNnmngp+tvrD8oQOMPA7T17Cp+SGkwfSRFdQJnomq8cYQWG1QDQrryI6tpqsn1hVo0wdwaAkRx7LOz/Nau5TzXeinaQneiJ42YH4VkQbVyVcawhMsuOrqTByp6yojFE45fu5tLimJNgjs=
