language: node_js
node_js:
- "8.12"

env:
  global:
    - TZ='Europe/Oslo'
    - DATE="$(date +%Y%m%d)"
    - TIME="$(date +%H%M)"
    - RELEASE_VERSION="$TRAVIS_COMMIT"
    - APPLICATION_NAME='fpsak-frontend'
    - DOCKER_IMAGE_FULL_NAME="navikt/$APPLICATION_NAME:$RELEASE_VERSION"

install:
- yarn install

before_script:
- yarn less:lint
- yarn build

script:
#- docker build -t $DOCKER_IMAGE_FULL_NAME ./packages/fpsak

before_deploy:
# Set up git user name and tag this commit
# bytte epost til nav
#- git config --local user.name "navikt"
#- git config --local user.email "petterruud@gmail.com"
#- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

services:
#  - docker

# bytt til dockerhub systembruker
deploy:
#  provider: script
#  skip_cleanup: true
#  script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push "$DOCKER_IMAGE_FULL_NAME"
#  on:
#    branch: master

after_deploy:
  #- git remote add auth-origin "https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}"
  #- git tag $RELEASE_VERSION
  #- git push auth-origin --tags

#deploy:
#  - provider: releases
#    skip-cleanup: true
#    github-token: $GITHUB_TOKEN
#    api_key: $GITHUB_TOKEN
#    on:
#      branch: master
#    keep-history: true
#    file_glob: true
#    file: dist/**/*
