language: node_js
node_js:
- "8.12"
cache:
  directories:
    - node_modules

install:
- yarn install --ignore-scripts

script:
- yarn less:lint
- yarn test
- yarn build

after_script:
  - chmod a+x ./_scripts/bump.sh
  - ./_scripts/bump.sh
