version: '3'
services:
  fpmock2:
    image: repo.adeo.no:5443/fpmock2:v201903011748
    ports:
      - 8060:8060
      - 8063:8063
    environment:
      - CUSTOM_KEYSTORE_PATH=/app/testcerts/vtpkeystore.jks
      - CUSTOM_KEYSTORE_PASSWORD=changeit
      - ENABLE_CUSTOM_TRUSTSTORE=true
      - AUTOTEST_OAUTH2_ISSUER=https://fpmock2:8063/isso/oauth2
      - AUTOTEST_FPSAK_BASE_URL=http://fpsak:8080
      - AUTOTEST_VTP_BASE_URL=http://fpmock2:8060
  fpsak:
    image: repo.adeo.no:5443/fpsak-for-vtp:v201903011747
    restart: on-failure
    links:
      - fpsak-oracle
      - fpmock2
    ports:
      - 8080:8080
    environment:
      - DEFAULTDS_URL=jdbc:oracle:thin:@fpsak-oracle:1521/XE
      - DVHDS_URL=jdbc:oracle:thin:@fpsak-oracle:1521/XE
  fpsak-oracle:
    image: repo.adeo.no:5443/fpsak-oracle:v201902281601
    shm_size: 1gb
    ports:
      - 1521:1521
