/**
 * ErrorEventType
 *
 * Dette er eventer som skal spesialformateres.
 */
export enum ErrorEventType {
  POLLING_TIMEOUT = 'POLLING_TIMEOUT',
  REQUEST_ERROR = 'REQUEST_ERROR',
  REQUEST_GATEWAY_TIMEOUT_OR_NOT_FOUND = 'REQUEST_GATEWAY_TIMEOUT_OR_NOT_FOUND',
  REQUEST_FORBIDDEN = 'REQUEST_FORBIDDEN',
  REQUEST_UNAUTHORIZED = 'REQUEST_UNAUTHORIZED',
}
