import type { AksjonspunktFraBackend } from '../AksjonspunktFraBackend';

export type UttakAp = AksjonspunktFraBackend<
  | 'FASTSETT_UTTAKPERIODER'
  | 'OVERSTYRING_AV_UTTAKPERIODER'
  | 'FASTSETT_UTTAK_STORTINGSREPRESENTANT'
  | 'KONTROLLER_REALITETSBEHANDLING_ELLER_KLAGE'
  | 'KONTROLLER_OPPLYSNINGER_OM_DØD'
  | 'KONTROLLER_OPPLYSNINGER_OM_SØKNADSFRIST'
>;
