// 5004, 5005, 5006, 5008, 5054, 5011,5013,5014,6004, 6010
export enum AksjonspunktKode {
  SJEKK_TERMINBEKREFTELSE = '5001',
  AVKLAR_DEKNINGSGRAD = '5002',
  MANUELL_VURDERING_AV_SØKNADSFRISTVILKÅRET = '5007',
  REGISTRER_PAPIRSØKNAD_ENGANGSSTØNAD = '5012',
  FORESLÅ_VEDTAK = '5015',
  FATTER_VEDTAK = '5016',
  SØKERS_OPPLYSNINGSPLIKT_MANU = '5017',
  VURDER_OMSORGSOVERTAKELSEVILKÅRET = '5018',
  VURDER_MEDLEMSKAPSVILKÅRET = '5101',
  VURDER_FORUTGÅENDE_MEDLEMSKAPSVILKÅR = '5102',
  VARSEL_REVURDERING_MANUELL = '5026',
  SJEKK_MANGLENDE_FØDSEL = '5027',
  OVERSTYRING_AV_FAKTA_OM_FØDSEL = '6019',
  FORESLÅ_VEDTAK_MANUELT = '5028',
  KONTROLLER_STOR_ETTERBETALING_SØKER = '5029',
  AVKLAR_VERGE = '5030',
  AVKLAR_OM_SØKER_HAR_MOTTATT_STØTTE = '5031',
  VURDERE_ANNEN_YTELSE_FØR_VEDTAK = '5033',
  VURDERE_DOKUMENT_FØR_VEDTAK = '5034',
  VURDERE_INNTEKTSMELDING_FØR_VEDTAK = '5003',
  MANUELL_VURDERING_AV_KLAGE_NFP = '5035',
  VURDER_INNSYN = '5037',
  REGISTRER_PAPIRSØKNAD_FORELDREPENGER = '5040',
  VURDER_PERMISJON_UTEN_SLUTTDATO = '5041',
  MANUELL_VURDERING_AV_SØKNADSFRIST = '5043',
  VURDER_PERIODER_MED_OPPTJENING = '5051',
  KONTROLLER_REVURDERINGSBEHANDLING_VARSEL_VED_UGUNST = '5055',
  REGISTRER_PAPIR_ENDRINGSØKNAD_FORELDREPENGER = '5057',
  REGISTRER_PAPIRSØKNAD_SVANGERSKAPSPENGER = '5096',
  MANUELL_KONTROLL_AV_OM_BRUKER_HAR_ALENEOMSORG = '5060',
  AVKLAR_LØPENDE_OMSORG = '5061',
  MANUELL_KONTROLL_AV_BESTEBEREGNING = '5062',
  FAKTA_UTTAK_GRADERING_UKJENT_AKTIVITET = '5063',
  FAKTA_UTTAK_INGEN_PERIODER = '5064',
  FAKTA_UTTAK_MANUELT_SATT_STARTDATO_ULIK_SØKNAD_STARTDATO = '5065',
  FAKTA_UTTAK_GRADERING_AKTIVITET_UTEN_BEREGNINGSGRUNNLAG = '5066',
  AUTOMATISK_MARKERING_AV_UTENLANDSSAK = '5068',
  AVKLAR_UTTAK_I_EØS_FOR_ANNENPART = '5103',
  FASTSETT_UTTAKPERIODER = '5071',
  FASTSETT_UTTAK_STORTINGSREPRESENTANT = '5072',
  KONTROLLER_REALITETSBEHANDLING_ELLER_KLAGE = '5073',
  VURDER_UTTAK_DOKUMENTASJON = '5074',
  KONTROLLER_OPPLYSNINGER_OM_DØD = '5076',
  KONTROLLER_OPPLYSNINGER_OM_SØKNADSFRIST = '5077',
  VURDERING_AV_FORMKRAV_KLAGE_NFP = '5082',
  VURDER_FEILUTBETALING = '5084',
  VURDER_ARBEIDSFORHOLD_INNTEKTSMELDING = '5085',
  AVKLAR_FAKTA_ANNEN_FORELDER_HAR_RETT = '5086',
  SØKERS_OPPLYSNINGSPLIKT_OVST = '6002',
  OVERSTYRING_AV_FØDSELSVILKÅRET = '6003',

  OVERSTYRING_AV_MEDLEMSKAPSVILKÅRET = '6005',
  OVERSTYRING_AV_FORUTGÅENDE_MEDLEMSKAPSVILKÅR = '6017',
  OVERSTYRING_AV_SØKNADSFRISTVILKÅRET = '6006',
  OVERSTYRING_AV_UTTAKPERIODER = '6008',
  OVERSTYRING_AV_FØDSELSVILKÅRET_FAR_MEDMOR = '6009',

  OVERSTYRING_AV_OPPTJENINGSVILKÅRET = '6011',
  OVERSTYRING_AV_DEKNINGSGRAD = '6016',
  OVERSTYRING_AV_RETT_OG_OMSORG = '6018',
  VURDER_OPPTJENINGSVILKÅRET = '5089',
  OVERSTYRING_AV_AVKLART_STARTDATO = '6045',
  OVERSTYRING_FAKTA_UTTAK = '6065',
  OVERSTYRING_AV_UTTAK_I_EØS_FOR_ANNENPART = '6103',
  AUTO_MANUELT_SATT_PÅ_VENT = '7001',
  AUTO_VENT_PÅ_FØDSELREGISTRERING = '7002',
  AUTO_VENTER_PÅ_KOMPLETT_SØKNAD = '7003',
  AUTO_VENT_ANKE_OVERSENDT_TIL_TRYGDERETTEN = '7033',
  VURDER_SVP_TILRETTELEGGING = '5091',
  MANUELL_VURDERING_AV_SVANGERSKAPSPENGERVILKÅRET = '5092',
  VURDER_FARESIGNALER = '5095',
  FASTSETT_BEREGNINGSGRUNNLAG_ARBEIDSTAKER_FRILANS = '5038',
  VURDER_VARIG_ENDRET_ELLER_NYOPPSTARTET_NÆRING_SELVSTENDIG_NÆRINGSDRIVENDE = '5039',
  FASTSETT_BEREGNINGSGRUNNLAG_TIDSBEGRENSET_ARBEIDSFORHOLD = '5047',
  FASTSETT_BEREGNINGSGRUNNLAG_FOR_SN_NY_I_ARBEIDSLIVET = '5049',
  VURDER_FAKTA_FOR_ATFL_SN = '5058',
  AVKLAR_AKTIVITETER = '5052',
  OVERSTYRING_AV_BEREGNINGSAKTIVITETER = '6014',
  OVERSTYRING_AV_BEREGNINGSGRUNNLAG = '6015',
  FORDEL_BEREGNINGSGRUNNLAG = '5046',
  VURDER_REFUSJON_BERGRUNN = '5059',

  /**
   * @deprecated: AVKLAR_ADOPSJONSDOKUMENTAJON
   */
  UTGÅTT_5004 = '5004',
  /**
   * @deprecated: AVKLAR_OM_ADOPSJON_GJELDER_EKTEFELLES_BARN
   */
  UTGÅTT_5005 = '5005',
  /**
   * @deprecated: AVKLAR_OM_SØKER_ER_MANN_SOM_ADOPTERER_ALENE
   */
  UTGÅTT_5006 = '5006',
  /**
   * @deprecated: AVKLAR_VILKÅR_FOR_OMSORGSOVERTAKELSE
   */
  UTGÅTT_5008 = '5008',
  /**
   * @deprecated: MANUELL_VURDERING_AV_OMSORGSVILKÅRET
   */
  UTGÅTT_5011 = '5011',
  /**
   * @deprecated: MANUELL_VURDERING_AV_FORELDREANSVARSVILKÅRET_2_LEDD
   */
  UTGÅTT_5013 = '5013',
  /**
   * @deprecated: MANUELL_VURDERING_AV_FORELDREANSVARSVILKÅRET_4_LEDD
   */
  UTGÅTT_5014 = '5014',
  /**
   * @deprecated: AVKLAR_LOVLIG_OPPHOLD
   */
  UTGÅTT_5019 = '5019',
  /**
   * @deprecated: AVKLAR_OM_BRUKER_ER_BOSATT
   */
  UTGÅTT_5020 = '5020',
  /**
   * @deprecated: AVKLAR_OM_BRUKER_HAR_GYLDIG_PERIODE
   */
  UTGÅTT_5021 = '5021',
  /**
   * @deprecated: AVKLAR_OPPHOLDSRETT
   */
  UTGÅTT_5023 = '5023',
  /**
   * @deprecated: VARSEL_REVURDERING_ETTERKONTROLL
   */
  UTGÅTT_5025 = '5025',
  /**
   * @deprecated: BEHANDLE_KLAGE_NK
   */
  UTGÅTT_5036 = '5036',
  /**
   * @deprecated: FASTSETT_BRUTTO_BEREGNINGSGRUNNLAG_SELVSTENDIG_NAERINGSDRIVENDE
   */
  UTGÅTT_5042 = '5042',
  /**
   * @deprecated: KONTROLLER_AUTOMATISK_BESTEBEREGNING
   */
  UTGÅTT_5048 = '5048',
  /**
   * @deprecated: VURDER_GRADERING_UTEN_BEREGNINGSGRUNNLAG
   */
  UTGÅTT_5050 = '5050',
  /**
   * @deprecated: AVKLAR_FORTSATT_MEDLEMSKAP
   */
  UTGÅTT_5053 = '5053',
  /**
   * @deprecated: AVKLAR_VILKÅR_FOR_FORELDREANSVAR
   */
  UTGÅTT_5054 = '5054',
  /**
   * @deprecated: KONTROLL_AV_MAUNELT_OPPRETTET_REVURDERINGSBEHANDLING
   */
  UTGÅTT_5056 = '5056',
  /**
   * @deprecated: TETTE_SAKER
   */
  UTGÅTT_5067 = '5067',
  /**
   * @deprecated: ANNENPART_EØS
   */
  UTGÅTT_5069 = '5069',
  /**
   * @deprecated: KONTROLLER_OPPLYSNINGER_OM_FORDELING_AV_STØNADSPERIODEN
   */
  UTGÅTT_5075 = '5075',
  /**
   * @deprecated: KONTROLLER_TILSTØTENDE_YTELSER_INNVILGET
   */
  UTGÅTT_5078 = '5078',
  /**
   * @deprecated: KONTROLLER_TILSTØTENDE_YTELSER_OPPHØRT
   */
  UTGÅTT_5079 = '5079',
  /**
   * @deprecated: VURDER_FORMKRAV_NK
   */
  UTGÅTT_5083 = '5083',
  /**
   * @deprecated: AVKLAR_ARBEIDSFORHOLD
   */
  UTGÅTT_5080 = '5080',
  /**
   * @deprecated: VURDER_TILBAKETREKK
   */
  UTGÅTT_5090 = '5090',

  /**
   * @deprecated: OVERSTYRING_AV_ADOPSJONSVILKÅRET
   */
  UTGÅTT_6004 = '6004',
  /**
   * @deprecated: OVERSTYRING_AV_ADOPSJONSVILKÅRET_FP
   */
  UTGÅTT_6010 = '6010',
  /**
   * @deprecated: OVERSTYR_LØPENDE_MEDLEMSKAPSVILKAR
   */
  UTGÅTT_6012 = '6012',

  /**
   * @deprecated: AUTO_VENT_GRADERING_UTEN_BEREGNINGSGRUNNLAG
   */
  UTGÅTT_7019 = '7019',
}

export type VilkårOverstyringAksjonspunkter =
  | AksjonspunktKode.OVERSTYRING_AV_SØKNADSFRISTVILKÅRET
  | AksjonspunktKode.OVERSTYRING_AV_FØDSELSVILKÅRET
  | AksjonspunktKode.OVERSTYRING_AV_MEDLEMSKAPSVILKÅRET
  | AksjonspunktKode.OVERSTYRING_AV_FORUTGÅENDE_MEDLEMSKAPSVILKÅR
  | AksjonspunktKode.UTGÅTT_6012
  | AksjonspunktKode.OVERSTYRING_AV_FØDSELSVILKÅRET_FAR_MEDMOR
  | AksjonspunktKode.OVERSTYRING_AV_OPPTJENINGSVILKÅRET;

export type OverstyringAksjonspunkter =
  | VilkårOverstyringAksjonspunkter
  | AksjonspunktKode.OVERSTYRING_AV_FAKTA_OM_FØDSEL;

const uttakAksjonspunkter = [
  AksjonspunktKode.OVERSTYRING_AV_UTTAKPERIODER,
  AksjonspunktKode.FASTSETT_UTTAKPERIODER,
  AksjonspunktKode.FASTSETT_UTTAK_STORTINGSREPRESENTANT,
  AksjonspunktKode.UTGÅTT_5067,
  AksjonspunktKode.UTGÅTT_5069,
  AksjonspunktKode.KONTROLLER_REALITETSBEHANDLING_ELLER_KLAGE,
  AksjonspunktKode.UTGÅTT_5075,
  AksjonspunktKode.KONTROLLER_OPPLYSNINGER_OM_DØD,
  AksjonspunktKode.KONTROLLER_OPPLYSNINGER_OM_SØKNADSFRIST,
  AksjonspunktKode.UTGÅTT_5078,
  AksjonspunktKode.UTGÅTT_5079,
];

const faktaUttakAksjonspunkter = [
  AksjonspunktKode.OVERSTYRING_FAKTA_UTTAK,
  AksjonspunktKode.FAKTA_UTTAK_GRADERING_UKJENT_AKTIVITET,
  AksjonspunktKode.FAKTA_UTTAK_INGEN_PERIODER,
  AksjonspunktKode.FAKTA_UTTAK_MANUELT_SATT_STARTDATO_ULIK_SØKNAD_STARTDATO,
  AksjonspunktKode.FAKTA_UTTAK_GRADERING_AKTIVITET_UTEN_BEREGNINGSGRUNNLAG,
];

const aksjonspunktIsOfType =
  (validAksjonspunktCodes: string[]) =>
  (aksjonspunktCode: string): boolean =>
    validAksjonspunktCodes.includes(aksjonspunktCode);

export const isUttakAksjonspunkt = aksjonspunktIsOfType(uttakAksjonspunkter);

export const isFaktaUttakAksjonspunkt = aksjonspunktIsOfType(faktaUttakAksjonspunkter);
