export enum AndreKriterierType {
  TIL_BESLUTTER = 'TIL_BESLUTTER',
  PAPIRSOKNAD = 'PAPIRSOKNAD',
  UTBETALING_TIL_BRUKER = 'UTBETALING_TIL_BRUKER',
  ENDRINGSSOKNAD = 'ENDRINGSSOKNAD',
  REVURDERING_INNTEKTSMELDING = 'REVURDERING_INNTEKTSMELDING',
  KLAGE_PÅ_TILBAKEBETALING = 'KLAGE_PÅ_TILBAKEBETALING',
  BERØRT_BEHANDLING = 'BERØRT_BEHANDLING',
  PLEIEPENGER = 'PLEIEPENGER',
  UTSATT_START = 'UTSATT_START',
}
