export enum AndreKriterierType {
  TIL_BESLUTTER = 'TIL_BESLUTTER',
  PAPIRSOKNAD = 'PAPIRSOKNAD',
  UTBETALING_TIL_BRUKER = 'UTBETALING_TIL_BRUKER',
  REVURDERING_INNTEKTSMELDING = 'REVURDERING_INNTEKTSMELDING',
}
