const ankeVurdering = {
  ANKE_AVVIS: 'ANKE_AVVIS',
  ANKE_STADFESTE_YTELSESVEDTAK: 'ANKE_STADFESTE_YTELSESVEDTAK',
  ANKE_OMGJOER: 'ANKE_OMGJOER',
  ANKE_OPPHEVE_OG_HJEMSENDE: 'ANKE_OPPHEVE_OG_HJEMSENDE',
  ANKE_HJEMSENDE_UTEN_OPPHEV: 'ANKE_HJEMSENDE_UTEN_OPPHEV',
};

export default ankeVurdering;
