enum ArbeidsforholdKomplettVurderingType {
  VENT_PÅ_INNTEKTSMELDING = 'VENT_PÅ_INNTEKTSMELDING',
  FORTSETT_UTEN_INNTEKTSMELDING = 'FORTSETT_UTEN_INNTEKTSMELDING',
  MANUELT_OPPRETTET_AV_SAKSBEHANDLER = 'MANUELT_OPPRETTET_AV_SAKSBEHANDLER',
  FJERN_FRA_BEHANDLINGEN = 'FJERN_FRA_BEHANDLINGEN',
}

export default ArbeidsforholdKomplettVurderingType;
