export enum BehandlingResultatTypeTilbakekreving {
  INGEN_TILBAKEBETALING = 'INGEN_TILBAKEBETALING',
  DELVIS_TILBAKEBETALING = 'DELVIS_TILBAKEBETALING',
  FULL_TILBAKEBETALING = 'FULL_TILBAKEBETALING',
  HENLAGT_FEILOPPRETTET = 'HENLAGT_FEILOPPRETTET',
  HENLAGT_FEILOPPRETTET_MED_BREV = 'HENLAGT_FEILOPPRETTET_MED_BREV',
  HENLAGT_FEILOPPRETTET_UTEN_BREV = 'HENLAGT_FEILOPPRETTET_UTEN_BREV',
}
