const behandlingArsakType = {
  // MANUELL OPPRETTING
  FEIL_I_LOVANDVENDELSE: 'RE-LOV',
  FEIL_REGELVERKSFORSTAELSE: 'RE-RGLF',
  FEIL_ELLER_ENDRET_FAKTA: 'RE-FEFAKTA',
  FEIL_PROSESSUELL: 'RE-PRSSL',
  ANNET: 'RE-ANNET',

  // Klage
  RE_KLAGE_UTEN_END_INNTEKT: 'RE-KLAG-U-INNTK',
  RE_KLAGE_MED_END_INNTEKT: 'RE-KLAG-M-INNTK',
  ETTER_KLAGE: 'ETTER_KLAGE',

  MEDLEMSKAP: 'RE-MDL',
  OPPTJENING: 'RE-OPTJ',
  FORDELING: 'RE-FRDLING',
  INNTEKT: 'RE-INNTK',
  FØDSEL: 'RE-FØDSEL',
  DØD: 'RE-DØD',
  SØKERS_RELASJON: 'RE-SRTB',
  SØKNADSFRIST: 'RE-FRIST',
  BEREEGNINGSGRUNNLAG: 'RE-BER-GRUN',

  // Hendelser
  RE_HENDELSE_FØDSEL: 'RE-HENDELSE-FØDSEL',
  RE_HENDELSE_DØD_FORELDER: 'RE-HENDELSE-DØD-F',
  RE_HENDELSE_DØD_BARN: 'RE-HENDELSE-DØD-B',
  RE_HENDELSE_DØDFØDSEL: 'RE-HENDELSE-DØDFØD',
  RE_HENDELSE_UTFLYTTING: 'RE-HENDELSE-UTFLYTTING',

  // Mottak
  RE_ENDRING_FRA_BRUKER: 'RE-END-FRA-BRUKER',
  RE_ENDRET_INNTEKTSMELDING: 'RE-END-INNTEKTSMELD',

  // Tekniske behandlinger som skal spesialbehandles i prosessen
  BERØRT_BEHANDLING: 'BERØRT-BEHANDLING',
  REBEREGN_FERIEPENGER: 'REBEREGN-FERIEPENGER',
  RE_UTSATT_START: 'RE-UTSATT-START',

  // Etterkontroll + funksjonell
  RE_MANGLER_FØDSEL: 'RE-MF',
  RE_MANGLER_FØDSEL_I_PERIODE: 'RE-MFIP',
  RE_AVVIK_ANTALL_BARN: 'RE-AVAB',
};

export const behandlingArsakTypeTilbakekreving = {
  RE_FEILUTBETALT_BELØP_REDUSERT: 'RE_FEILUTBETALT_BELØP_REDUSERT',
  RE_FORELDELSE: 'RE_FORELDELSE',
  RE_KLAGE_KA: 'RE_KLAGE_KA',
  RE_KLAGE_NFP: 'RE_KLAGE_NFP',
  RE_VILKÅR: 'RE_VILKÅR',
};

export default behandlingArsakType;
