export enum BehandlingType {
  FORSTEGANGSSOKNAD = 'BT-002',
  KLAGE = 'BT-003',
  REVURDERING = 'BT-004',
  DOKUMENTINNSYN = 'BT-006',
  TILBAKEKREVING = 'BT-007',
  ANKE = 'BT-008',
  TILBAKEKREVING_REVURDERING = 'BT-009',
}
