const dokumentMalType = {
  INNHENT_DOK: 'INNHEN',
  INNOPP: 'INNOPP',
  REVURDERING_DOK: 'REVURD',
  VARREV: 'VARREV',
  FORLENGET_DOK: 'FORLEN',
  FORLENGET_SAKSBEHANDLINGSTID: 'FORSAK',
  FORLENGET_MEDL_DOK: 'FORLME',
  FORLENGET_SAKSBEHANDLINGSTID_MEDL: 'FORMED',
  KLAGE_OMGJORING: 'KOMGJO',
  KLAGE_AVVIST: 'KAVVIS',
  KLAGE_STADFESTET: 'KSTADF',
  KLAGE_YTELSESVEDTAK_OPPHEVET: 'KHJEMS',
  KLAGE_OVERSENDT_KLAGEINSTANS: 'KOVKLA',
  ANKE_VEDTAK_OMGJORING: 'VEDOGA',
  ANKE_BESLUTNING_OM_OPPHEVING: 'ANKEBO',
  TBKVAR: 'TBKVAR',
  KORRIGVARS: 'KORRIGVARS',
  FRITKS: 'FRITKS',
  VARSEL_OM_TILBAKEKREVING: 'VARS',
};

export default dokumentMalType;
