const dokumentMalType = {
  INNHENTE_OPPLYSNINGER: 'INNOPP',
  VARSEL_OM_REVURDERING: 'VARREV',
  FORLENGET_SAKSBEHANDLINGSTID: 'FORSAK',
  FORLENGET_SAKSBEHANDLINGSTID_MEDL: 'FORMED',
  KLAGE_OMGJORING: 'KGEOMG',
  KLAGE_AVVIST: 'KGEAVV',
  KLAGE_STADFESTET: 'KGESTA',
  KLAGE_HJEMSENDT: 'KGEHJE',
  KLAGE_OVERSENDT: 'KGEOVE',
  ANKE_OMGJORT: 'ANKOMG',
  ANKE_OPPHEVET: 'ANKOPP',
  FRITEKST: 'FRITEK',
  INNSYN_SVAR: 'INNSYN',
  INFO_OM_HENLEGGELSE: 'IOHENL',
  TBK_INNHENTE_OPPLYSNINGER: 'INNHEN',
  KORRIGERT_VARSEL_OM_TILBAKEKREVING: 'KORRIGVARS',
  VARSEL_OM_TILBAKEKREVING: 'VARS',
};

export default dokumentMalType;
