const dokumentMalType = {
  INNHENTE_OPPLYSNINGER: 'INNOPP',
  VARSEL_OM_REVURDERING: 'VARREV',
  FORLENGET_DOK: 'FORLEN',
  FORLENGET_SAKSBEHANDLINGSTID: 'FORSAK',
  FORLENGET_MEDL_DOK: 'FORLME',
  FORLENGET_SAKSBEHANDLINGSTID_MEDL: 'FORMED',
  KLAGE_OMGJORING: 'KGEOMG',
  KLAGE_AVVIST: 'KGEAVV',
  KLAGE_STADFESTET: 'KGESTA',
  KLAGE_YTELSESVEDTAK_OPPHEVET: 'KGEHJE',
  KLAGE_OVERSENDT_KLAGEINSTANS: 'KGEOVE',
  ANKE_VEDTAK_OMGJORING: 'ANKOMG',
  ANKE_BESLUTNING_OM_OPPHEVING: 'ANKOPP',
  TBKVAR: 'TBKVAR',
  KORRIGVARS: 'KORRIGVARS',
  FRITEKST: 'FRITEK',
  VARSEL_OM_TILBAKEKREVING: 'VARS',
  INNSYN: 'INNSYN',
  IOHENL: 'IOHENL',
};

export default dokumentMalType;
