enum FagsakMarkeringKode {
  NASJONAL = 'NASJONAL',
  EØS_BOSATT_NORGE = 'EØS_BOSATT_NORGE',
  BOSATT_UTLAND = 'BOSATT_UTLAND',
  SAMMENSATT_KONTROLL = 'SAMMENSATT_KONTROLL',
  DØD_DØDFØDSEL = 'DØD_DØDFØDSEL',
  SELVSTENDIG_NÆRING = 'SELVSTENDIG_NÆRING'
}

export default FagsakMarkeringKode;
