const faktaOmBeregningTilfelle = {
  FASTSETT_BESTEBEREGNING_FODENDE_KVINNE: 'FASTSETT_BESTEBEREGNING_FØDENDE_KVINNE',
  FASTSETT_BG_ARBEIDSTAKER_UTEN_INNTEKTSMELDING: 'FASTSETT_BG_ARBEIDSTAKER_UTEN_INNTEKTSMELDING',
  FASTSETT_BG_KUN_YTELSE: 'FASTSETT_BG_KUN_YTELSE',
  FASTSETT_ENDRET_BEREGNINGSGRUNNLAG: 'FASTSETT_ENDRET_BEREGNINGSGRUNNLAG',
  FASTSETT_ETTERLONN_SLUTTPAKKE: 'FASTSETT_ETTERLØNN_SLUTTPAKKE',
  FASTSETT_MAANEDSINNTEKT_FL: 'FASTSETT_MAANEDSINNTEKT_FL',
  FASTSETT_MAANEDSLONN_ARBEIDSTAKER_UTEN_INNTEKTSMELDING: 'FASTSETT_MÅNEDSLØNN_ARBEIDSTAKER_UTEN_INNTEKTSMELDING',
  TILSTØTENDE_YTELSE: 'TILSTØTENDE_YTELSE',
  VURDER_AT_OG_FL_I_SAMME_ORGANISASJON: 'VURDER_AT_OG_FL_I_SAMME_ORGANISASJON',
  VURDER_BESTEBEREGNING: 'VURDER_BESTEBEREGNING',
  VURDER_ETTERLONN_SLUTTPAKKE: 'VURDER_ETTERLØNN_SLUTTPAKKE',
  VURDER_LONNSENDRING: 'VURDER_LØNNSENDRING',
  VURDER_MOTTAR_YTELSE: 'VURDER_MOTTAR_YTELSE',
  VURDER_MILITÆR_SIVILTJENESTE: 'VURDER_MILITÆR_SIVILTJENESTE',
  VURDER_NYOPPSTARTET_FL: 'VURDER_NYOPPSTARTET_FL',
  VURDER_REFUSJONSKRAV_SOM_HAR_KOMMET_FOR_SENT: 'VURDER_REFUSJONSKRAV_SOM_HAR_KOMMET_FOR_SENT',
  VURDER_SN_NY_I_ARBEIDSLIVET: 'VURDER_SN_NY_I_ARBEIDSLIVET',
  VURDER_TIDSBEGRENSET_ARBEIDSFORHOLD: 'VURDER_TIDSBEGRENSET_ARBEIDSFORHOLD',
};

export default faktaOmBeregningTilfelle;
