export enum FarSøkerType {
  ANDRE_FORELDER_DØD = 'ANDRE_FORELDER_DØD',
  OVERTATT_OMSORG_F = 'OVERTATT_OMSORG_F',
  ADOPTERER_ALENE = 'ADOPTERER_ALENE',
  OVERTATT_OMSORG = 'OVERTATT_OMSORG',
  ANDRE_FORELD_DØD_F = 'ANDRE_FORELD_DØD_F',
}
