export enum Inntektskategori {
  ARBEIDSTAKER = 'ARBEIDSTAKER',
  FRILANSER = 'FRILANSER',
  SELVSTENDIG_NÆRINGSDRIVENDE = 'SELVSTENDIG_NÆRINGSDRIVENDE',
  DAGPENGER = 'DAGPENGER',
  ARBEIDSAVKLARINGSPENGER = 'ARBEIDSAVKLARINGSPENGER',
  SJØMANN = 'SJØMANN',
  DAGMAMMA = 'DAGMAMMA',
  JORDBRUKER = 'JORDBRUKER',
  FISKER = 'FISKER',
  ARBEIDSTAKER_UTEN_FERIEPENGER = 'ARBEIDSTAKER_UTEN_FERIEPENGER',
  UDEFINERT = '-',
}

const SELVSTENDIG_NÆRINGSDRIVENDE_INNTEKTSKATEGORIER = [
  Inntektskategori.SELVSTENDIG_NÆRINGSDRIVENDE,
  Inntektskategori.JORDBRUKER,
  Inntektskategori.DAGMAMMA,
  Inntektskategori.FISKER,
];

export const isSelvstendigNæringsdrivende = (inntektskategori: string): boolean =>
  SELVSTENDIG_NÆRINGSDRIVENDE_INNTEKTSKATEGORIER.some(i => i === inntektskategori);
