const konsekvensForYtelsen = {
  ENDRING_I_BEREGNING: 'ENDRING_I_BEREGNING',
  ENDRING_I_UTTAK: 'ENDRING_I_UTTAK',
  ENDRING_I_FORDELING_AV_YTELSEN: 'ENDRING_I_FORDELING_AV_YTELSEN',
  INGEN_ENDRING: 'INGEN_ENDRING',
  ENDRING_I_BEREGNING_OG_UTTAK: 'ENDRING_I_BEREGNING_OG_UTTAK',
  FORELDREPENGER_OPPHORER: 'FORELDREPENGER_OPPHØRER',
  UDEFINERT: '-',
};

export default konsekvensForYtelsen;
