export enum OppgaveBehandlingStatus {
  UNDER_ARBEID = 'UNDER_ARBEID',
  PÅ_VENT = 'PÅ_VENT',
  FERDIG = 'FERDIG',
  TIL_BESLUTTER = 'TIL_BESLUTTER',
  RETURNERT_FRA_BESLUTTER = 'RETURNERT_FRA_BESLUTTER',
}
