export enum OppholdArsakType {
  INGEN = 'INGEN',
  UTTAK_MØDREKVOTE_ANNEN_FORELDER = 'UTTAK_MØDREKVOTE_ANNEN_FORELDER',
  UTTAK_FEDREKVOTE_ANNEN_FORELDER = 'UTTAK_FEDREKVOTE_ANNEN_FORELDER',
  UTTAK_FELLESP_ANNEN_FORELDER = 'UTTAK_FELLESP_ANNEN_FORELDER',
  UTTAK_FORELDREPENGER_ANNEN_FORELDER = 'UTTAK_FORELDREPENGER_ANNEN_FORELDER',
  UDEFINERT = '-',
}
