export enum OppholdArsakType {
  INGEN = 'INGEN',
  UTTAK_MØDREKVOTE_ANNEN_FORELDER = 'UTTAK_MØDREKVOTE_ANNEN_FORELDER',
  UTTAK_FEDREKVOTE_ANNEN_FORELDER = 'UTTAK_FEDREKVOTE_ANNEN_FORELDER',
  UTTAK_FELLESP_ANNEN_FORELDER = 'UTTAK_FELLESP_ANNEN_FORELDER',
  UTTAK_FORELDREPENGER_ANNEN_FORELDER = 'UTTAK_FORELDREPENGER_ANNEN_FORELDER',
  UDEFINERT = '-',
}

//TODO (TOR) Bør desse ligga her?
export enum OppholdArsakKontoNavn {
  INGEN = 'Ingen årsak',
  UTTAK_MØDREKVOTE_ANNEN_FORELDER = 'Mødrekvote',
  UTTAK_FEDREKVOTE_ANNEN_FORELDER = 'Fedrekvote',
  UTTAK_FELLESP_ANNEN_FORELDER = 'Fellesperiode',
  UTTAK_FORELDREPENGER_ANNEN_FORELDER = 'Foreldrepenger',
  UDEFINERT = '-',
}

export enum OppholdArsakMapper {
  INGEN = 'UDEFINERT',
  UTTAK_MØDREKVOTE_ANNEN_FORELDER = 'MØDREKVOTE',
  UTTAK_FEDREKVOTE_ANNEN_FORELDER = 'FEDREKVOTE',
  UTTAK_FELLESP_ANNEN_FORELDER = 'FELLESPERIODE',
  UTTAK_FORELDREPENGER_ANNEN_FORELDER = 'FORELDREPENGER',
}
