enum OpplysningAdresseType {
  BOSTEDSADRESSE = 'BOSTEDSADRESSE',
  POSTADRESSE = 'POSTADRESSE',
  POSTADRESSE_UTLAND = 'POSTADRESSE_UTLAND',
  MIDLERTIDIG_POSTADRESSE_NORGE = 'MIDLERTIDIG_POSTADRESSE_NORGE',
  MIDLERTIDIG_POSTADRESSE_UTLAND = 'MIDLERTIDIG_POSTADRESSE_UTLAND',
  UKJENT_ADRESSE = 'UKJENT_ADRESSE',
}

export default OpplysningAdresseType;
