export enum OverforingArsak {
  INSTITUSJONSOPPHOLD_ANNEN_FORELDER = 'INSTITUSJONSOPPHOLD_ANNEN_FORELDER',
  SYKDOM_ANNEN_FORELDER = 'SYKDOM_ANNEN_FORELDER',
  ALENEOMSORG = 'ALENEOMSORG',
  IKKE_RETT_ANNEN_FORELDER = 'IKKE_RETT_ANNEN_FORELDER',
  UDEFINERT = '-',
}
