export enum PermisjonsbeskrivelseType {
  PERMISJON = 'PERMISJON',
  PERMITTERING = 'PERMITTERING',
  PERMISJON_VED_MILITÆRTJENESTE = 'PERMISJON_VED_MILITÆRTJENESTE',
  UTDANNINGSPERMISJON_LOVFESTET = 'UTDANNINGSPERMISJON_LOVFESTET',
  UTDANNINGSPERMISJON = 'UTDANNINGSPERMISJON',
  UTDANNINGSPERMISJON_IKKE_LOVFESTET = 'UTDANNINGSPERMISJON_IKKE_LOVFESTET',
  VELFERDSPERMISJON = 'VELFERDSPERMISJON',
  ANNEN_PERMISJON_LOVFESTET = 'ANNEN_PERMISJON_LOVFESTET',
  PERMISJON_MED_FORELDREPENGER = 'PERMISJON_MED_FORELDREPENGER',
  ANNEN_PERMISJON_IKKE_LOVFESTET = 'ANNEN_PERMISJON_IKKE_LOVFESTET',
}
