export enum PersonstatusType {
  DOD = 'DØD',
  BOSATT = 'BOSA',
  UTVANDRET = 'UTVA',
  AKTIVTBOSTNR = 'ABNR',
  AKTIVT = 'ADNR',
  FORSVUNNET = 'FOSV',
  FODSELSREGISTRERT = 'FØDR',
  UFULLSTENDIGFNR = 'UFUL',
  UREGISTRERT = 'UREG',
  UTGATTANNULLERT = 'UTAN',
  UTGATTPERSON = 'UTPE',
  UDEFINERT = '-',
}
