export enum SkjermlenkeTypeTilbakekreving {
  FAKTA_OM_FEILUTBETALING = 'FAKTA_OM_FEILUTBETALING',
  TILBAKEKREVING = 'TILBAKEKREVING',
  VEDTAK = 'VEDTAK',
  FORELDELSE = 'FORELDELSE',
  FAKTA_OM_VERGE = 'FAKTA_OM_VERGE',
}
