export enum SkjermlenkeType {
  VEDTAK = 'VEDTAK',
  FAKTA_OM_MEDLEMSKAP = 'FAKTA_OM_MEDLEMSKAP',
  FAKTA_UTTAK = 'FAKTA_UTTAK',
  KLAGE_BEH_NFP = 'KLAGE_BEH_NFP',
  FORMKRAV_KLAGE_NFP = 'FORMKRAV_KLAGE_NFP',
  PUNKT_FOR_MEDLEMSKAP_LØPENDE = 'PUNKT_FOR_MEDLEMSKAP_LØPENDE',
}
