const stonadskontoType = {
  FELLESPERIODE: 'FELLESPERIODE',
  MODREKVOTE: 'MØDREKVOTE',
  FEDREKVOTE: 'FEDREKVOTE',
  FORELDREPENGER: 'FORELDREPENGER',
  UTEN_AKTIVITETSKRAV: 'UTEN_AKTIVITETSKRAV',
  MINSTERETT_NESTE_STØNADSPERIODE: 'MINSTERETT_NESTE_STØNADSPERIODE',
  MINSTERETT: 'MINSTERETT',
  FLERBARNSDAGER: 'FLERBARNSDAGER',
  FORELDREPENGER_FOR_FODSEL: 'FORELDREPENGER_FØR_FØDSEL',
  UDEFINERT: '-',
};

export default stonadskontoType;
