enum StonadskontoType {
  FELLESPERIODE = 'FELLESPERIODE',
  MØDREKVOTE = 'MØDREKVOTE',
  FEDREKVOTE = 'FEDREKVOTE',
  FORELDREPENGER = 'FORELDREPENGER',
  UTEN_AKTIVITETSKRAV = 'UTEN_AKTIVITETSKRAV',
  MINSTERETT_NESTE_STØNADSPERIODE = 'MINSTERETT_NESTE_STØNADSPERIODE',
  MINSTERETT = 'MINSTERETT',
  FLERBARNSDAGER = 'FLERBARNSDAGER',
  FORELDREPENGER_FØR_FØDSEL = 'FORELDREPENGER_FØR_FØDSEL',
  UDEFINERT = '-',
}

export default StonadskontoType;
