export enum TilbakekrevingKodeverkType {
  AKTSOMHET = 'Aktsomhet',
  SARLIG_GRUNN = 'SærligGrunn',
  VILKAR_RESULTAT = 'VilkårResultat',
  FORELDELSE_VURDERING = 'ForeldelseVurderingType',
  HENDELSE_TYPE = 'HendelseType',
  HENDELSE_UNDERTYPE = 'HendelseUnderType',
  TILBAKEKR_VIDERE_BEH = 'VidereBehandling',
  VENT_AARSAK = 'Venteårsak',
  SKJERMLENKE_TYPE = 'SkjermlenkeType',
  VEDTAK_RESULTAT_TYPE = 'VedtakResultatType',
  VURDER_AARSAK = 'VurderÅrsak',
  VERGE_TYPE = 'VergeType',
  HISTORIKK_AKTOER = 'HistorikkAktør',
}
