export enum TilbakekrevingVidereBehandling {
  TILBAKEKR_OPPRETT = 'TILBAKEKR_OPPRETT',
  TILBAKEKR_IGNORER = 'TILBAKEKR_IGNORER',
  TILBAKEKR_INNTREKK = 'TILBAKEKR_INNTREKK',
  TILBAKEKR_OPPDATER = 'TILBAKEKR_OPPDATER',
}
