export enum UtsettelseArsakCode {
  ARBEID = 'ARBEID',
  LOVBESTEMT_FERIE = 'LOVBESTEMT_FERIE',
  SYKDOM = 'SYKDOM',
  INSTITUSJONSOPPHOLD_SØKER = 'INSTITUSJONSOPPHOLD_SØKER',
  INSTITUSJONSOPPHOLD_BARNET = 'INSTITUSJONSOPPHOLD_BARNET',
  HV_OVELSE = 'HV_OVELSE',
  NAV_TILTAK = 'NAV_TILTAK',
  UDEFINERT = '-',
}
