const uttakPeriodeType = {
  MODREKVOTE: 'MØDREKVOTE',
  FEDREKVOTE: 'FEDREKVOTE',
  FELLESPERIODE: 'FELLESPERIODE',
  FORELDREPENGER_FOR_FODSEL: 'FORELDREPENGER_FØR_FØDSEL',
  FORELDREPENGER: 'FORELDREPENGER',
};

export default uttakPeriodeType;
