export enum UttakPeriodeType {
  MODREKVOTE = 'MØDREKVOTE',
  FEDREKVOTE = 'FEDREKVOTE',
  FELLESPERIODE = 'FELLESPERIODE',
  FORELDREPENGER_FOR_FODSEL = 'FORELDREPENGER_FØR_FØDSEL',
  FORELDREPENGER = 'FORELDREPENGER',
  UDEFINERT = '-',
}
