const vedtakResultatType = {
  INGEN_TILBAKEBETALING: 'INGEN_TILBAKEBETALING',
  DELVIS_TILBAKEBETALING: 'DELVIS_TILBAKEBETALING',
  FULL_TILBAKEBETALING: 'FULL_TILBAKEBETALING',
};

export default vedtakResultatType;
