export enum VurderPaNyttArsakType {
  FEIL_FAKTA = 'FEIL_FAKTA',
  FEIL_LOV = 'FEIL_LOV',
  FEIL_REGEL = 'FEIL_REGEL',
  SKJØNN = 'SKJØNN',
  UTREDNING = 'UTREDNING',
  SAKSFLYT = 'SAKSFLYT',
  BEGRUNNELSE = 'BEGRUNNELSE',
  ANNET = 'ANNET',
}
