// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/fplos` | (string & {});
};

export type tjenester_avdelingsleder_dto_AvdelingDto = {
  avdelingEnhet: string;
  kreverKode6: boolean;
  navn: string;
};

export type avdelingsleder_innlogget_InnloggetNavAnsattDto = {
  brukernavn?: string;
  kanOppgavestyre?: boolean;
  navn?: string;
};

export type tjenester_avdelingsleder_dto_InitLinksDto = {
  avdelinger?: Array<tjenester_avdelingsleder_dto_AvdelingDto>;
  innloggetBruker?: avdelingsleder_innlogget_InnloggetNavAnsattDto;
};

export type statistikk_AktiveOgTilgjenglige = {
  aktive?: number;
  tidspunkt?: string;
  tilgjengelige?: number;
  ventende?: number;
};

export type tjenester_felles_dto_SakslisteIdDto = {
  sakslisteId: number;
};

export type tjenester_avdelingsleder_dto_AvdelingEnhetDto = {
  avdelingEnhet: string;
};

export type oppgave_BehandlingType = 'BT-002' | 'BT-003' | 'BT-004' | 'BT-006' | 'BT-007' | 'BT-008' | 'BT-009';

export type tjenester_avdelingsleder_nøkkeltall_dto_BehandlingVenteStatus = 'PÅ_VENT' | 'IKKE_PÅ_VENT';

export type tjenester_avdelingsleder_nøkkeltall_dto_NøkkeltallBehandlingFørsteUttakDto = {
  antall?: number;
  behandlingType?: oppgave_BehandlingType;
  behandlingVenteStatus?: tjenester_avdelingsleder_nøkkeltall_dto_BehandlingVenteStatus;
  førsteUttakMåned?: string;
};

export type oppgave_FagsakYtelseType = 'ES' | 'FP' | 'SVP';

export type tjenester_avdelingsleder_nøkkeltall_dto_OppgaverForAvdeling = {
  antall?: number;
  behandlingType?: oppgave_BehandlingType;
  fagsakYtelseType?: oppgave_FagsakYtelseType;
  tilBehandling?: boolean;
};

export type tjenester_avdelingsleder_nøkkeltall_dto_NøkkeltallBehandlingVentefristUtløperDto = {
  antall?: number;
  fagsakYtelseType?: oppgave_FagsakYtelseType;
  fristUke?: string;
};

export type tjenester_avdelingsleder_nøkkeltall_dto_OppgaverForAvdelingPerDato = {
  antall?: number;
  behandlingType?: oppgave_BehandlingType;
  fagsakYtelseType?: oppgave_FagsakYtelseType;
  opprettetDato?: string;
};

export type tjenester_avdelingsleder_nøkkeltall_dto_OppgaverForFørsteStønadsdagUkeMåned = {
  antall?: number;
  fagsakYtelseType?: oppgave_FagsakYtelseType;
  førsteStønadsdag?: string;
};

export type tjenester_felles_dto_ReservasjonDto = {
  begrunnelse?: string;
  behandlingType?: oppgave_BehandlingType;
  flyttetAvIdent?: string;
  flyttetAvNavn?: string;
  flyttetTidspunkt?: string;
  oppgaveId?: number;
  oppgaveSaksNr?: string;
  reservertAvIdent?: string;
  reservertAvNavn?: string;
  reservertTilTidspunkt?: string;
};

export type tjenester_saksbehandler_oppgave_dto_OppgaveIdDto = {
  oppgaveId: number;
};

export type tjenester_avdelingsleder_saksbehandler_dto_SaksbehandlerGruppeNavneEndringRequestDto = {
  avdelingEnhet?: tjenester_avdelingsleder_dto_AvdelingEnhetDto;
  gruppeId?: number;
  gruppeNavn: string;
};

export type tjenester_avdelingsleder_dto_SaksbehandlerOgGruppeDto = {
  avdelingEnhet: tjenester_avdelingsleder_dto_AvdelingEnhetDto;
  brukerIdent: tjenester_felles_dto_SaksbehandlerBrukerIdentDto;
  gruppeId?: number;
};

export type tjenester_felles_dto_SaksbehandlerBrukerIdentDto = {
  brukerIdent: string;
};

export type tjenester_felles_dto_SaksbehandlerDto = {
  ansattAvdeling?: string;
  brukerIdent: string;
  navn?: string;
};

export type tjenester_avdelingsleder_saksbehandler_dto_SaksbehandlerGruppeDto = {
  gruppeId: number;
  gruppeNavn: string;
  saksbehandlere: Array<tjenester_felles_dto_SaksbehandlerDto>;
};

export type tjenester_avdelingsleder_saksbehandler_dto_SaksbehandlereOgSaksbehandlerGrupper = {
  saksbehandlerGrupper: Array<tjenester_avdelingsleder_saksbehandler_dto_SaksbehandlerGruppeDto>;
};

export type tjenester_avdelingsleder_dto_SaksbehandlerOgAvdelingDto = {
  avdelingEnhet: tjenester_avdelingsleder_dto_AvdelingEnhetDto;
  brukerIdent: tjenester_felles_dto_SaksbehandlerBrukerIdentDto;
};

export type tjenester_avdelingsleder_saksbehandler_dto_SaksbehandlerGruppeSletteRequestDto = {
  avdelingEnhet?: tjenester_avdelingsleder_dto_AvdelingEnhetDto;
  gruppeId?: number;
};

export type oppgave_AndreKriterierType =
  | 'VURDER_SYKDOM'
  | 'PLEIEPENGER'
  | 'BARE_FAR_RETT'
  | 'MOR_UKJENT_UTLAND'
  | 'UTSATT_START'
  | 'PRAKSIS_UTSETTELSE'
  | 'BERØRT_BEHANDLING'
  | 'ENDRINGSSOKNAD'
  | 'PAPIRSOKNAD'
  | 'UTBETALING_TIL_BRUKER'
  | 'VURDER_FARESIGNALER'
  | 'VURDER_EØS_OPPTJENING'
  | 'ARBEID_INNTEKT'
  | 'NÆRING'
  | 'REVURDERING_INNTEKTSMELDING'
  | 'TERMINBEKREFTELSE'
  | 'NYTT_VEDTAK'
  | 'KLAGE_PÅ_TILBAKEBETALING'
  | 'VURDER_FORMKRAV'
  | 'IKKE_VARSLET'
  | 'OVER_FIRE_RETTSGEBYR'
  | 'TIL_BESLUTTER'
  | 'SAMMENSATT_KONTROLL'
  | 'UTLANDSSAK'
  | 'EØS_SAK'
  | 'KODE7_SAK'
  | 'RETURNERT_FRA_BESLUTTER'
  | 'DØD'
  | 'HASTER';

export type oppgave_Periodefilter = 'RELATIV_PERIODE_DAGER' | 'RELATIV_PERIODE_MÅNEDER' | 'FAST_PERIODE';

export type oppgavekø_KøSortering =
  | 'BEHFRIST'
  | 'OPPRBEH'
  | 'FORSTONAD'
  | 'FORSTONAD_SYNK'
  | 'BELOP'
  | 'FEILUTBETALINGSTART'
  | 'OPPGAVE_OPPRETTET';

export type oppgavekø_KøSortering_FeltType = 'HELTALL' | 'DATO' | 'DATO_UTEN_FILTER';

export type tjenester_avdelingsleder_saksliste_dto_SorteringDto = {
  fomDato?: string;
  fra?: number;
  periodefilter: oppgave_Periodefilter;
  sorteringType: oppgavekø_KøSortering;
  til?: number;
  tomDato?: string;
};

export type tjenester_felles_dto_KøSorteringFeltDto = {
  feltType: oppgavekø_KøSortering_FeltType;
  sorteringType: oppgavekø_KøSortering;
};

export type tjenester_felles_dto_SakslisteDto = {
  andreKriterie: tjenester_felles_dto_SakslisteDto_AndreKriterieDto;
  behandlingTyper: Array<oppgave_BehandlingType>;
  fagsakYtelseTyper: Array<oppgave_FagsakYtelseType>;
  gjeldendeStatistikk?: tjenester_felles_dto_SakslisteDto_StatistikkDto;
  navn: string;
  saksbehandlere: Array<tjenester_felles_dto_SaksbehandlerDto>;
  sakslisteId: number;
  sortering: tjenester_avdelingsleder_saksliste_dto_SorteringDto;
  sorteringTyper: Array<tjenester_felles_dto_KøSorteringFeltDto>;
};

export type tjenester_felles_dto_SakslisteDto_AndreKriterieDto = {
  ekskluder: Array<oppgave_AndreKriterierType>;
  inkluder: Array<oppgave_AndreKriterierType>;
};

export type tjenester_felles_dto_SakslisteDto_StatistikkDto = {
  alleOppgaver?: number;
  behandlingerPåVent?: number;
  tilgjengeligeOppgaver?: number;
};

export type tjenester_avdelingsleder_saksliste_dto_SakslisteLagreDto = {
  andreKriterie: tjenester_avdelingsleder_saksliste_dto_SakslisteLagreDto_AndreKriterieDto;
  avdelingEnhet: string;
  behandlingTyper?: Array<oppgave_BehandlingType>;
  fagsakYtelseTyper?: Array<oppgave_FagsakYtelseType>;
  navn: string;
  sakslisteId: number;
  sortering: tjenester_avdelingsleder_saksliste_dto_SakslisteLagreDto_SorteringDto;
};

export type tjenester_avdelingsleder_saksliste_dto_SakslisteLagreDto_AndreKriterieDto = {
  ekskluder?: Array<oppgave_AndreKriterierType>;
  inkluder?: Array<oppgave_AndreKriterierType>;
};

export type tjenester_avdelingsleder_saksliste_dto_SakslisteLagreDto_SorteringDto = {
  fomDato?: string;
  fra?: number;
  periodefilter: oppgave_Periodefilter;
  sorteringType: oppgavekø_KøSortering;
  til?: number;
  tomDato?: string;
};

export type tjenester_avdelingsleder_saksliste_dto_SakslisteSaksbehandlerDto = {
  avdelingEnhet: tjenester_avdelingsleder_dto_AvdelingEnhetDto;
  brukerIdent: tjenester_felles_dto_SaksbehandlerBrukerIdentDto;
  checked?: boolean;
  sakslisteId: tjenester_felles_dto_SakslisteIdDto;
};

export type tjenester_avdelingsleder_saksliste_dto_SakslisteOgAvdelingDto = {
  avdelingEnhet: tjenester_avdelingsleder_dto_AvdelingEnhetDto;
  sakslisteId: tjenester_felles_dto_SakslisteIdDto;
};

export type tjenester_kodeverk_KodeverkRestTjeneste_KriterieFilterDto = {
  andreKriterierType?: oppgave_AndreKriterierType;
  valgbarForBehandlingTyper?: Array<oppgave_BehandlingType>;
  valgbarForYtelseTyper?: Array<oppgave_FagsakYtelseType>;
};

export type vedtak_hendelser_behandling_Aksjonspunktstatus = 'AVBRUTT' | 'OPPRETTET' | 'UTFØRT';

export type vedtak_hendelser_behandling_Aksjonspunkttype =
  | 'AKSJONSPUNKT'
  | 'OVERSTYRING'
  | 'BESLUTTER'
  | 'PAPIRSØKNAD'
  | 'VENT';

export type vedtak_hendelser_behandling_Behandlingsstatus =
  | 'OPPRETTET'
  | 'UTREDES'
  | 'FATTER_VEDTAK'
  | 'IVERKSETTER_VEDTAK'
  | 'AVSLUTTET';

export type vedtak_hendelser_behandling_Behandlingstype =
  | 'FØRSTEGANGS'
  | 'REVURDERING'
  | 'TILBAKEBETALING'
  | 'TILBAKEBETALING_REVURDERING'
  | 'KLAGE'
  | 'ANKE'
  | 'INNSYN';

export type vedtak_hendelser_behandling_Behandlingsårsak =
  | 'SØKNAD'
  | 'INNTEKTSMELDING'
  | 'FOLKEREGISTER'
  | 'PLEIEPENGER'
  | 'ETTERKONTROLL'
  | 'MANUELL'
  | 'BERØRT'
  | 'UTSATT_START'
  | 'OPPHØR_NY_SAK'
  | 'REGULERING'
  | 'KLAGE_OMGJØRING'
  | 'KLAGE_TILBAKEBETALING'
  | 'ANNET';

export type vedtak_hendelser_behandling_Kildesystem = 'FPSAK' | 'FPTILBAKE';

export type vedtak_hendelser_behandling_Ytelse = 'ENGANGSTØNAD' | 'FORELDREPENGER' | 'SVANGERSKAPSPENGER';

export type vedtak_hendelser_behandling_los_LosBehandlingDto = {
  aksjonspunkt?: Array<vedtak_hendelser_behandling_los_LosBehandlingDto_LosAksjonspunktDto>;
  aktørId: string;
  ansvarligSaksbehandlerIdent?: string;
  avsluttetTidspunkt?: string;
  behandlendeEnhetId?: string;
  behandlingUuid: string;
  behandlingsegenskaper?: Array<string>;
  behandlingsfrist?: string;
  behandlingsstatus: vedtak_hendelser_behandling_Behandlingsstatus;
  behandlingstype: vedtak_hendelser_behandling_Behandlingstype;
  behandlingsårsaker?: Array<vedtak_hendelser_behandling_Behandlingsårsak>;
  faresignaler?: boolean;
  foreldrepengerDto?: vedtak_hendelser_behandling_los_LosBehandlingDto_LosForeldrepengerDto;
  kildesystem: vedtak_hendelser_behandling_Kildesystem;
  opprettetTidspunkt: string;
  refusjonskrav?: boolean;
  saksegenskaper?: Array<string>;
  saksnummer: string;
  tilbakeDto?: vedtak_hendelser_behandling_los_LosBehandlingDto_LosTilbakeDto;
  ytelse: vedtak_hendelser_behandling_Ytelse;
};

export type vedtak_hendelser_behandling_los_LosBehandlingDto_LosAksjonspunktDto = {
  definisjon?: string;
  fristTid?: string;
  status?: vedtak_hendelser_behandling_Aksjonspunktstatus;
  type?: vedtak_hendelser_behandling_Aksjonspunkttype;
};

export type vedtak_hendelser_behandling_los_LosBehandlingDto_LosForeldrepengerDto = {
  førsteUttakDato?: string;
};

export type vedtak_hendelser_behandling_los_LosBehandlingDto_LosTilbakeDto = {
  feilutbetaltBeløp?: number;
  førsteFeilutbetalingDato?: string;
};

export type tjenester_felles_dto_FlyttetReservasjonDto = {
  begrunnelse?: string;
  flyttetAvIdent?: string;
  navn?: string;
  tidspunkt?: string;
};

export type tjenester_felles_dto_ReservasjonStatusDto = {
  erReservert?: boolean;
  erReservertAvInnloggetBruker?: boolean;
  flyttetReservasjon?: tjenester_felles_dto_FlyttetReservasjonDto;
  reservertAvIdent?: string;
  reservertAvNavn?: string;
  reservertTilTidspunkt?: string;
};

export type tjenester_reservasjon_dto_ReservasjonEndringRequestDto = {
  oppgaveId: tjenester_saksbehandler_oppgave_dto_OppgaveIdDto;
  reserverTil: string;
};

export type tjenester_saksbehandler_oppgave_dto_OppgaveFlyttingDto = {
  begrunnelse: string;
  brukerIdent: tjenester_felles_dto_SaksbehandlerBrukerIdentDto;
  oppgaveId: tjenester_saksbehandler_oppgave_dto_OppgaveIdDto;
};

export type domene_typer_Fagsystem = 'FPSAK' | 'FPTILBAKE';

export type tjenester_felles_dto_OppgaveDto = {
  andreKriterier?: Array<oppgave_AndreKriterierType>;
  behandlingId?: string;
  behandlingsfrist?: string;
  behandlingstype?: oppgave_BehandlingType;
  erTilSaksbehandling?: boolean;
  fagsakYtelseType?: oppgave_FagsakYtelseType;
  id?: number;
  navn?: string;
  opprettetTidspunkt?: string;
  personnummer?: string;
  reservasjonStatus?: tjenester_felles_dto_ReservasjonStatusDto;
  saksnummer?: string;
  system?: domene_typer_Fagsystem;
};

export type tjenester_felles_dto_OppgaveBehandlingStatus =
  | 'PÅ_VENT'
  | 'FERDIG'
  | 'TIL_BESLUTTER'
  | 'RETURNERT_FRA_BESLUTTER'
  | 'UNDER_ARBEID';

export type tjenester_felles_dto_OppgaveDtoMedStatus = {
  andreKriterier?: Array<oppgave_AndreKriterierType>;
  behandlingId?: string;
  behandlingsfrist?: string;
  behandlingstype?: oppgave_BehandlingType;
  erTilSaksbehandling?: boolean;
  fagsakYtelseType?: oppgave_FagsakYtelseType;
  id?: number;
  navn?: string;
  oppgaveBehandlingStatus?: tjenester_felles_dto_OppgaveBehandlingStatus;
  opprettetTidspunkt?: string;
  personnummer?: string;
  reservasjonStatus?: tjenester_felles_dto_ReservasjonStatusDto;
  saksnummer?: string;
  system?: domene_typer_Fagsystem;
};

export type tjenester_felles_dto_AsyncPollingStatus = {
  cancelUri?: string;
  eta?: string;
  location?: string;
  message?: string;
  pollIntervalMillis?: number;
  readOnly?: boolean;
  status?: tjenester_felles_dto_AsyncPollingStatus_Status;
};

export type tjenester_felles_dto_AsyncPollingStatus_Status =
  | 'PENDING'
  | 'COMPLETE'
  | 'DELAYED'
  | 'CANCELLED'
  | 'HALTED';

export type tjenester_saksbehandler_oppgave_dto_OppgaveIderDto = {
  oppgaveIder: string;
};

export type tjenester_saksbehandler_oppgave_dto_SaknummerIderDto = {
  saksnummerListe: string;
};

export type HentAvdelingerData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/avdelingsleder/avdelinger';
};

export type HentAvdelingerResponses = {
  /**
   * default response
   */
  default: Array<tjenester_avdelingsleder_dto_AvdelingDto>;
};

export type HentAvdelingerResponse = HentAvdelingerResponses[keyof HentAvdelingerResponses];

export type HentInitielleRessurserData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/avdelingsleder/init-fetch';
};

export type HentInitielleRessurserResponses = {
  /**
   * default response
   */
  default: tjenester_avdelingsleder_dto_InitLinksDto;
};

export type HentInitielleRessurserResponse = HentInitielleRessurserResponses[keyof HentInitielleRessurserResponses];

export type AktiveOgTilgjengligeOppgaverStatistikkForKøData = {
  body?: never;
  path?: never;
  query: {
    sakslisteId: tjenester_felles_dto_SakslisteIdDto;
    avdelingEnhet: tjenester_avdelingsleder_dto_AvdelingEnhetDto;
  };
  url: '/api/avdelingsleder/nøkkeltall/statistikk-oppgave-filter';
};

export type AktiveOgTilgjengligeOppgaverStatistikkForKøResponses = {
  /**
   * default response
   */
  default: Array<statistikk_AktiveOgTilgjenglige>;
};

export type AktiveOgTilgjengligeOppgaverStatistikkForKøResponse =
  AktiveOgTilgjengligeOppgaverStatistikkForKøResponses[keyof AktiveOgTilgjengligeOppgaverStatistikkForKøResponses];

export type GetAlleBehandlingerForAvdelingData = {
  body?: never;
  path?: never;
  query: {
    avdelingEnhet: tjenester_avdelingsleder_dto_AvdelingEnhetDto;
  };
  url: '/api/avdelingsleder/nøkkeltall/åpne-behandlinger';
};

export type GetAlleBehandlingerForAvdelingResponses = {
  /**
   * default response
   */
  default: Array<tjenester_avdelingsleder_nøkkeltall_dto_NøkkeltallBehandlingFørsteUttakDto>;
};

export type GetAlleBehandlingerForAvdelingResponse =
  GetAlleBehandlingerForAvdelingResponses[keyof GetAlleBehandlingerForAvdelingResponses];

export type GetAlleOppgaverForAvdelingData = {
  body?: never;
  path?: never;
  query: {
    avdelingEnhet: tjenester_avdelingsleder_dto_AvdelingEnhetDto;
  };
  url: '/api/avdelingsleder/nøkkeltall/behandlinger-under-arbeid';
};

export type GetAlleOppgaverForAvdelingResponses = {
  /**
   * default response
   */
  default: Array<tjenester_avdelingsleder_nøkkeltall_dto_OppgaverForAvdeling>;
};

export type GetAlleOppgaverForAvdelingResponse =
  GetAlleOppgaverForAvdelingResponses[keyof GetAlleOppgaverForAvdelingResponses];

export type GetAlleVentefristerForAvdelingData = {
  body?: never;
  path?: never;
  query: {
    avdelingEnhet: tjenester_avdelingsleder_dto_AvdelingEnhetDto;
  };
  url: '/api/avdelingsleder/nøkkeltall/frist-utløp';
};

export type GetAlleVentefristerForAvdelingResponses = {
  /**
   * default response
   */
  default: Array<tjenester_avdelingsleder_nøkkeltall_dto_NøkkeltallBehandlingVentefristUtløperDto>;
};

export type GetAlleVentefristerForAvdelingResponse =
  GetAlleVentefristerForAvdelingResponses[keyof GetAlleVentefristerForAvdelingResponses];

export type GetAntallOppgaverForAvdelingPerDatoData = {
  body?: never;
  path?: never;
  query: {
    avdelingEnhet: tjenester_avdelingsleder_dto_AvdelingEnhetDto;
  };
  url: '/api/avdelingsleder/nøkkeltall/behandlinger-under-arbeid-historikk';
};

export type GetAntallOppgaverForAvdelingPerDatoResponses = {
  /**
   * default response
   */
  default: Array<tjenester_avdelingsleder_nøkkeltall_dto_OppgaverForAvdelingPerDato>;
};

export type GetAntallOppgaverForAvdelingPerDatoResponse =
  GetAntallOppgaverForAvdelingPerDatoResponses[keyof GetAntallOppgaverForAvdelingPerDatoResponses];

export type GetOppgaverPerFørsteStønadsdagMånedData = {
  body?: never;
  path?: never;
  query: {
    avdelingEnhet: tjenester_avdelingsleder_dto_AvdelingEnhetDto;
  };
  url: '/api/avdelingsleder/nøkkeltall/behandlinger-første-stønadsdag-mnd';
};

export type GetOppgaverPerFørsteStønadsdagMånedResponses = {
  /**
   * default response
   */
  default: Array<tjenester_avdelingsleder_nøkkeltall_dto_OppgaverForFørsteStønadsdagUkeMåned>;
};

export type GetOppgaverPerFørsteStønadsdagMånedResponse =
  GetOppgaverPerFørsteStønadsdagMånedResponses[keyof GetOppgaverPerFørsteStønadsdagMånedResponses];

export type HentAntallOppgaverForAvdelingData = {
  body?: never;
  path?: never;
  query: {
    avdelingEnhet: tjenester_avdelingsleder_dto_AvdelingEnhetDto;
  };
  url: '/api/avdelingsleder/oppgaver/avdelingantall';
};

export type HentAntallOppgaverForAvdelingResponses = {
  /**
   * default response
   */
  default: number;
};

export type HentAntallOppgaverForAvdelingResponse =
  HentAntallOppgaverForAvdelingResponses[keyof HentAntallOppgaverForAvdelingResponses];

export type HentAntallOppgaverForSakslisteData = {
  body?: never;
  path?: never;
  query: {
    sakslisteId: tjenester_felles_dto_SakslisteIdDto;
    avdelingEnhet: tjenester_avdelingsleder_dto_AvdelingEnhetDto;
  };
  url: '/api/avdelingsleder/oppgaver/antall';
};

export type HentAntallOppgaverForSakslisteResponses = {
  /**
   * default response
   */
  default: number;
};

export type HentAntallOppgaverForSakslisteResponse =
  HentAntallOppgaverForSakslisteResponses[keyof HentAntallOppgaverForSakslisteResponses];

export type HentAvdelingensReservasjonerData = {
  body?: never;
  path?: never;
  query: {
    avdelingEnhet: tjenester_avdelingsleder_dto_AvdelingEnhetDto;
  };
  url: '/api/avdelingsleder/reservasjoner';
};

export type HentAvdelingensReservasjonerResponses = {
  /**
   * default response
   */
  default: Array<tjenester_felles_dto_ReservasjonDto>;
};

export type HentAvdelingensReservasjonerResponse =
  HentAvdelingensReservasjonerResponses[keyof HentAvdelingensReservasjonerResponses];

export type OpphevOppgaveReservasjonData = {
  /**
   * Id for oppgave som reservasjonen er tilknyttet
   */
  body: tjenester_saksbehandler_oppgave_dto_OppgaveIdDto;
  path?: never;
  query?: never;
  url: '/api/avdelingsleder/reservasjoner/opphev';
};

export type OpphevOppgaveReservasjonResponses = {
  /**
   * default response
   */
  default: unknown;
};

export type EndreSaksbehandlerGruppeData = {
  body?: tjenester_avdelingsleder_saksbehandler_dto_SaksbehandlerGruppeNavneEndringRequestDto;
  path?: never;
  query?: never;
  url: '/api/avdelingsleder/saksbehandlere/grupper/endre-gruppenavn';
};

export type EndreSaksbehandlerGruppeResponses = {
  /**
   * default response
   */
  default: unknown;
};

export type FjernSaksbehandlerFraGruppeData = {
  body?: tjenester_avdelingsleder_dto_SaksbehandlerOgGruppeDto;
  path?: never;
  query?: never;
  url: '/api/avdelingsleder/saksbehandlere/grupper/fjern-saksbehandler';
};

export type FjernSaksbehandlerFraGruppeResponses = {
  /**
   * default response
   */
  default: unknown;
};

export type HentAvdelingensSaksbehandlereData = {
  body?: never;
  path?: never;
  query: {
    avdelingEnhet: tjenester_avdelingsleder_dto_AvdelingEnhetDto;
  };
  url: '/api/avdelingsleder/saksbehandlere';
};

export type HentAvdelingensSaksbehandlereResponses = {
  /**
   * default response
   */
  default: Array<tjenester_felles_dto_SaksbehandlerDto>;
};

export type HentAvdelingensSaksbehandlereResponse =
  HentAvdelingensSaksbehandlereResponses[keyof HentAvdelingensSaksbehandlereResponses];

export type LeggTilNySaksbehandlerData = {
  /**
   * Brukeridentifikasjon og avdelingsid
   */
  body: tjenester_avdelingsleder_dto_SaksbehandlerOgAvdelingDto;
  path?: never;
  query?: never;
  url: '/api/avdelingsleder/saksbehandlere';
};

export type LeggTilNySaksbehandlerResponses = {
  /**
   * default response
   */
  default: unknown;
};

export type HentSaksbehandlerGrupperData = {
  body?: never;
  path?: never;
  query: {
    avdelingEnhet: tjenester_avdelingsleder_dto_AvdelingEnhetDto;
  };
  url: '/api/avdelingsleder/saksbehandlere/grupper';
};

export type HentSaksbehandlerGrupperResponses = {
  /**
   * default response
   */
  default: tjenester_avdelingsleder_saksbehandler_dto_SaksbehandlereOgSaksbehandlerGrupper;
};

export type HentSaksbehandlerGrupperResponse =
  HentSaksbehandlerGrupperResponses[keyof HentSaksbehandlerGrupperResponses];

export type LeggSaksbehandlerTilGruppeData = {
  body?: tjenester_avdelingsleder_dto_SaksbehandlerOgGruppeDto;
  path?: never;
  query?: never;
  url: '/api/avdelingsleder/saksbehandlere/grupper/legg-til-saksbehandler';
};

export type LeggSaksbehandlerTilGruppeResponses = {
  /**
   * default response
   */
  default: unknown;
};

export type OppdaterSaksbehandlerData = {
  /**
   * Brukeridentifikasjon og avdelingsid
   */
  body: tjenester_avdelingsleder_dto_SaksbehandlerOgAvdelingDto;
  path?: never;
  query?: never;
  url: '/api/avdelingsleder/saksbehandlere/oppdater';
};

export type OppdaterSaksbehandlerResponses = {
  /**
   * default response
   */
  default: unknown;
};

export type OpprettSaksbehandlerGruppeData = {
  body?: tjenester_avdelingsleder_dto_AvdelingEnhetDto;
  path?: never;
  query?: never;
  url: '/api/avdelingsleder/saksbehandlere/grupper/opprett-gruppe';
};

export type OpprettSaksbehandlerGruppeResponses = {
  /**
   * default response
   */
  default: tjenester_avdelingsleder_saksbehandler_dto_SaksbehandlerGruppeDto;
};

export type OpprettSaksbehandlerGruppeResponse =
  OpprettSaksbehandlerGruppeResponses[keyof OpprettSaksbehandlerGruppeResponses];

export type SlettSaksbehandlerData = {
  /**
   * Brukeridentifikasjon og avdelingsid
   */
  body: tjenester_avdelingsleder_dto_SaksbehandlerOgAvdelingDto;
  path?: never;
  query?: never;
  url: '/api/avdelingsleder/saksbehandlere/slett';
};

export type SlettSaksbehandlerResponses = {
  /**
   * default response
   */
  default: unknown;
};

export type SlettSaksbehandlerGruppeData = {
  body?: tjenester_avdelingsleder_saksbehandler_dto_SaksbehandlerGruppeSletteRequestDto;
  path?: never;
  query?: never;
  url: '/api/avdelingsleder/saksbehandlere/grupper/slett-saksbehandlergruppe';
};

export type SlettSaksbehandlerGruppeResponses = {
  /**
   * default response
   */
  default: unknown;
};

export type SøkAvdelingensSaksbehandlereData = {
  /**
   * Brukeridentifikasjon
   */
  body: tjenester_felles_dto_SaksbehandlerBrukerIdentDto;
  path?: never;
  query?: never;
  url: '/api/avdelingsleder/saksbehandlere/søk';
};

export type SøkAvdelingensSaksbehandlereResponses = {
  /**
   * default response
   */
  default: tjenester_felles_dto_SaksbehandlerDto;
};

export type SøkAvdelingensSaksbehandlereResponse =
  SøkAvdelingensSaksbehandlereResponses[keyof SøkAvdelingensSaksbehandlereResponses];

export type HentAvdelingensSakslisterData = {
  body?: never;
  path?: never;
  query: {
    avdelingEnhet: tjenester_avdelingsleder_dto_AvdelingEnhetDto;
  };
  url: '/api/avdelingsleder/sakslister';
};

export type HentAvdelingensSakslisterResponses = {
  /**
   * default response
   */
  default: Array<tjenester_felles_dto_SakslisteDto>;
};

export type HentAvdelingensSakslisterResponse =
  HentAvdelingensSakslisterResponses[keyof HentAvdelingensSakslisterResponses];

export type OpprettNySakslisteData = {
  /**
   * enhet til avdelingsenheten som det skal opprettes ny saksliste for
   */
  body: tjenester_avdelingsleder_dto_AvdelingEnhetDto;
  path?: never;
  query?: never;
  url: '/api/avdelingsleder/sakslister';
};

export type OpprettNySakslisteResponses = {
  /**
   * default response
   */
  default: tjenester_felles_dto_SakslisteIdDto;
};

export type OpprettNySakslisteResponse = OpprettNySakslisteResponses[keyof OpprettNySakslisteResponses];

export type LagreNavnData = {
  body: tjenester_avdelingsleder_saksliste_dto_SakslisteLagreDto;
  path?: never;
  query?: never;
  url: '/api/avdelingsleder/sakslister/endre';
};

export type LagreNavnResponses = {
  /**
   * default response
   */
  default: unknown;
};

export type LeggSaksbehandlerTilSakslisteData = {
  /**
   * Knytning mellom saksbehandler og saksliste
   */
  body: tjenester_avdelingsleder_saksliste_dto_SakslisteSaksbehandlerDto;
  path?: never;
  query?: never;
  url: '/api/avdelingsleder/sakslister/saksbehandler';
};

export type LeggSaksbehandlerTilSakslisteResponses = {
  /**
   * default response
   */
  default: unknown;
};

export type SlettSakslisteData = {
  /**
   * id til sakslisten som skal slettes
   */
  body: tjenester_avdelingsleder_saksliste_dto_SakslisteOgAvdelingDto;
  path?: never;
  query?: never;
  url: '/api/avdelingsleder/sakslister/slett';
};

export type SlettSakslisteResponses = {
  /**
   * default response
   */
  default: unknown;
};

export type HentGruppertKodelisteData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/kodeverk';
};

export type HentGruppertKodelisteResponses = {
  /**
   * default response
   */
  default: unknown;
};

export type HentKriterieFilterData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/kodeverk/kriterie-filter';
};

export type HentKriterieFilterResponses = {
  /**
   * default response
   */
  default: {
    [key: string]: tjenester_kodeverk_KodeverkRestTjeneste_KriterieFilterDto;
  };
};

export type HentKriterieFilterResponse = HentKriterieFilterResponses[keyof HentKriterieFilterResponses];

export type LagreBehandlingData = {
  body: vedtak_hendelser_behandling_los_LosBehandlingDto;
  path?: never;
  query?: never;
  url: '/api/migrering/lagrebehandling';
};

export type LagreBehandlingResponses = {
  /**
   * default response
   */
  default: unknown;
};

export type EndreOppgaveReservasjonData = {
  /**
   * forleng til dato
   */
  body: tjenester_reservasjon_dto_ReservasjonEndringRequestDto;
  path?: never;
  query?: never;
  url: '/api/reservasjon/endre-varighet';
};

export type EndreOppgaveReservasjonResponses = {
  /**
   * default response
   */
  default: tjenester_felles_dto_ReservasjonStatusDto;
};

export type EndreOppgaveReservasjonResponse = EndreOppgaveReservasjonResponses[keyof EndreOppgaveReservasjonResponses];

export type FlyttOppgaveReservasjonData = {
  /**
   * id, begrunnelse og brukerident
   */
  body: tjenester_saksbehandler_oppgave_dto_OppgaveFlyttingDto;
  path?: never;
  query?: never;
  url: '/api/reservasjon/flytt-reservasjon';
};

export type FlyttOppgaveReservasjonResponses = {
  /**
   * default response
   */
  default: tjenester_felles_dto_ReservasjonStatusDto;
};

export type FlyttOppgaveReservasjonResponse = FlyttOppgaveReservasjonResponses[keyof FlyttOppgaveReservasjonResponses];

export type ForlengOppgaveReservasjonData = {
  /**
   * id til oppgaven
   */
  body: tjenester_saksbehandler_oppgave_dto_OppgaveIdDto;
  path?: never;
  query?: never;
  url: '/api/reservasjon/forleng';
};

export type ForlengOppgaveReservasjonResponses = {
  /**
   * default response
   */
  default: tjenester_felles_dto_ReservasjonStatusDto;
};

export type ForlengOppgaveReservasjonResponse =
  ForlengOppgaveReservasjonResponses[keyof ForlengOppgaveReservasjonResponses];

export type GetReserverteOppgaverData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/reservasjon/reserverte-oppgaver';
};

export type GetReserverteOppgaverResponses = {
  /**
   * default response
   */
  default: Array<tjenester_felles_dto_OppgaveDto>;
};

export type GetReserverteOppgaverResponse = GetReserverteOppgaverResponses[keyof GetReserverteOppgaverResponses];

export type HentReservasjonData = {
  body?: never;
  path?: never;
  query: {
    /**
     * id til oppgaven
     */
    oppgaveId: tjenester_saksbehandler_oppgave_dto_OppgaveIdDto;
  };
  url: '/api/reservasjon/reservasjon-status';
};

export type HentReservasjonResponses = {
  /**
   * default response
   */
  default: tjenester_felles_dto_ReservasjonStatusDto;
};

export type HentReservasjonResponse = HentReservasjonResponses[keyof HentReservasjonResponses];

export type OpphevReservasjonTilknyttetOppgaveData = {
  /**
   * Id og begrunnelse
   */
  body: tjenester_saksbehandler_oppgave_dto_OppgaveIdDto;
  path?: never;
  query?: never;
  url: '/api/reservasjon/opphev-reservasjon';
};

export type OpphevReservasjonTilknyttetOppgaveResponses = {
  /**
   * default response
   */
  default: tjenester_felles_dto_ReservasjonStatusDto;
};

export type OpphevReservasjonTilknyttetOppgaveResponse =
  OpphevReservasjonTilknyttetOppgaveResponses[keyof OpphevReservasjonTilknyttetOppgaveResponses];

export type ReserverOppgaveData = {
  /**
   * id til oppgaven
   */
  body: tjenester_saksbehandler_oppgave_dto_OppgaveIdDto;
  path?: never;
  query?: never;
  url: '/api/reservasjon/reserver';
};

export type ReserverOppgaveResponses = {
  /**
   * default response
   */
  default: tjenester_felles_dto_ReservasjonStatusDto;
};

export type ReserverOppgaveResponse = ReserverOppgaveResponses[keyof ReserverOppgaveResponses];

export type SisteReserverteData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * vise kun aktive
     */
    kunAktive?: boolean;
  };
  url: '/api/reservasjon/tidligere-reserverte';
};

export type SisteReserverteResponses = {
  /**
   * default response
   */
  default: Array<tjenester_felles_dto_OppgaveDtoMedStatus>;
};

export type SisteReserverteResponse = SisteReserverteResponses[keyof SisteReserverteResponses];

export type SøkAvdelingensSaksbehandlere1Data = {
  /**
   * Brukeridentifikasjon
   */
  body: tjenester_felles_dto_SaksbehandlerBrukerIdentDto;
  path?: never;
  query?: never;
  url: '/api/reservasjon/flytt-reservasjon/søk';
};

export type SøkAvdelingensSaksbehandlere1Responses = {
  /**
   * default response
   */
  default: tjenester_felles_dto_SaksbehandlerDto;
};

export type SøkAvdelingensSaksbehandlere1Response =
  SøkAvdelingensSaksbehandlere1Responses[keyof SøkAvdelingensSaksbehandlere1Responses];

export type GetOppgaverTilBehandlingData = {
  body?: never;
  path?: never;
  query: {
    sakslisteId: tjenester_felles_dto_SakslisteIdDto;
  };
  url: '/api/saksbehandler/oppgaver/resultat';
};

export type GetOppgaverTilBehandlingResponses = {
  /**
   * Returnerer Oppgaver
   */
  200: tjenester_felles_dto_OppgaveDto;
};

export type GetOppgaverTilBehandlingResponse =
  GetOppgaverTilBehandlingResponses[keyof GetOppgaverTilBehandlingResponses];

export type HentAntallOppgaverForSaksliste1Data = {
  body?: never;
  path?: never;
  query: {
    sakslisteId: tjenester_felles_dto_SakslisteIdDto;
  };
  url: '/api/saksbehandler/oppgaver/antall';
};

export type HentAntallOppgaverForSaksliste1Responses = {
  /**
   * default response
   */
  default: number;
};

export type HentAntallOppgaverForSaksliste1Response =
  HentAntallOppgaverForSaksliste1Responses[keyof HentAntallOppgaverForSaksliste1Responses];

export type HentNesteOppgaverOgSjekkOmDisseErNyeData = {
  body?: never;
  path?: never;
  query: {
    sakslisteId: tjenester_felles_dto_SakslisteIdDto;
    oppgaveIder?: tjenester_saksbehandler_oppgave_dto_OppgaveIderDto;
  };
  url: '/api/saksbehandler/oppgaver/status';
};

export type HentNesteOppgaverOgSjekkOmDisseErNyeResponses = {
  /**
   * Returnerer Status
   */
  200: tjenester_felles_dto_AsyncPollingStatus;
};

export type HentNesteOppgaverOgSjekkOmDisseErNyeResponse =
  HentNesteOppgaverOgSjekkOmDisseErNyeResponses[keyof HentNesteOppgaverOgSjekkOmDisseErNyeResponses];

export type HentOppgaverData = {
  body?: never;
  path?: never;
  query: {
    sakslisteId: tjenester_felles_dto_SakslisteIdDto;
    oppgaveIder?: tjenester_saksbehandler_oppgave_dto_OppgaveIderDto;
  };
  url: '/api/saksbehandler/oppgaver';
};

export type HentOppgaverResponses = {
  /**
   * Hent oppgaver initiert, Returnerer link til å polle etter nye oppgaver
   */
  202: unknown;
};

export type HentOppgaverForFagsakerData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Liste med saksnummer
     */
    saksnummerListe: tjenester_saksbehandler_oppgave_dto_SaknummerIderDto;
  };
  url: '/api/saksbehandler/oppgaver/oppgaver-for-fagsaker';
};

export type HentOppgaverForFagsakerResponses = {
  /**
   * default response
   */
  default: Array<tjenester_felles_dto_OppgaveDto>;
};

export type HentOppgaverForFagsakerResponse = HentOppgaverForFagsakerResponses[keyof HentOppgaverForFagsakerResponses];

export type HentSakslisterData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/saksbehandler/saksliste';
};

export type HentSakslisterResponses = {
  /**
   * default response
   */
  default: Array<tjenester_felles_dto_SakslisteDto>;
};

export type HentSakslisterResponse = HentSakslisterResponses[keyof HentSakslisterResponses];
