import type { foreldrepenger_behandlingslager_behandling_aksjonspunkt_AksjonspunktDefinisjon } from './fpsak.gen';

export type AksjonspunktDefinisjon = foreldrepenger_behandlingslager_behandling_aksjonspunkt_AksjonspunktDefinisjon;
