import type { foreldrepenger_behandlingslager_behandling_aksjonspunkt_AksjonspunktStatus } from './apiDtoGenerert';

export type AksjonspunktStatus = foreldrepenger_behandlingslager_behandling_aksjonspunkt_AksjonspunktStatus;
