import type { foreldrepenger_behandlingslager_behandling_aksjonspunkt_AksjonspunktType } from './apiDtoGenerert';

export type AksjonspunktType = foreldrepenger_behandlingslager_behandling_aksjonspunkt_AksjonspunktType;
