import type { foreldrepenger_behandlingslager_behandling_aktivitetskrav_AktivitetskravPermisjonType } from './fpsak.gen';

export type AktivitetskravPermisjonType =
  foreldrepenger_behandlingslager_behandling_aktivitetskrav_AktivitetskravPermisjonType;
