import type {
  foreldrepenger_behandlingslager_behandling_anke_AnkeOmgjørÅrsak,
  foreldrepenger_behandlingslager_behandling_anke_AnkeVurdering,
  foreldrepenger_behandlingslager_behandling_anke_AnkeVurderingOmgjør,
  tjenester_behandling_anke_AnkebehandlingDto,
} from './fpsak.gen';

export type AnkeVurdering = tjenester_behandling_anke_AnkebehandlingDto;

export type AnkeVurderingOmgjoer = foreldrepenger_behandlingslager_behandling_anke_AnkeVurderingOmgjør;

export type AnkeVurderingType = foreldrepenger_behandlingslager_behandling_anke_AnkeVurdering;

export type AnkeOmgjørÅrsak = foreldrepenger_behandlingslager_behandling_anke_AnkeOmgjørÅrsak;
