//TODO: hvorfor ikke generert?
export type Arbeidskategori =
  | 'FISKER'
  | 'ARBEIDSTAKER'
  | 'SELVSTENDIG_NÆRINGSDRIVENDE'
  | 'KOMBINASJON_ARBEIDSTAKER_OG_SELVSTENDIG_NÆRINGSDRIVENDE'
  | 'SJØMANN'
  | 'JORDBRUKER'
  | 'DAGPENGER'
  | 'INAKTIV'
  | 'KOMBINASJON_ARBEIDSTAKER_OG_JORDBRUKER'
  | 'KOMBINASJON_ARBEIDSTAKER_OG_FISKER'
  | 'FRILANSER'
  | 'KOMBINASJON_ARBEIDSTAKER_OG_FRILANSER'
  | 'KOMBINASJON_ARBEIDSTAKER_OG_DAGPENGER'
  | 'DAGMAMMA'
  | 'ANNET';
