export type BehandlingResultatTypeTilbakekreving =
  | 'INGEN_TILBAKEBETALING'
  | 'DELVIS_TILBAKEBETALING'
  | 'FULL_TILBAKEBETALING'
  | 'HENLAGT_FEILOPPRETTET'
  | 'HENLAGT_FEILOPPRETTET_MED_BREV'
  | 'HENLAGT_FEILOPPRETTET_UTEN_BREV';
