import type {
  folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_AktivitetTomDatoMappingDto,
  folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_AndelForFaktaOmBeregningDto,
  folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_ArbeidstakerUtenInntektsmeldingAndelDto,
  folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_ATogFLISammeOrganisasjonDto,
  folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_AvklarAktiviteterDto,
  folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_BeregningAktivitetDto,
  folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_FaktaOmBeregningAndelDto,
  folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_FaktaOmBeregningDto,
  folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_KortvarigeArbeidsforholdDto,
  folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_KunYtelseDto,
  folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_RefusjonskravForSentDto,
  folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_VurderBesteberegningDto,
  folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_VurderMottarYtelseDto,
} from './fpsak.gen';

export type FaktaOmBeregningAndel =
  folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_FaktaOmBeregningAndelDto;

export type AndelForFaktaOmBeregning =
  folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_AndelForFaktaOmBeregningDto;

export type RefusjonskravSomKommerForSentListe =
  folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_RefusjonskravForSentDto;

export type VurderBesteberegning = folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_VurderBesteberegningDto;

export type BeregningAktivitet = folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_BeregningAktivitetDto;

export type AvklarBeregningAktiviteter =
  folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_AktivitetTomDatoMappingDto;

export type AvklarBeregningAktiviteterMap =
  folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_AvklarAktiviteterDto;

export type KortvarigAndel = folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_KortvarigeArbeidsforholdDto;

export type ArbeidstakerUtenIMAndel =
  folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_ArbeidstakerUtenInntektsmeldingAndelDto;

export type KunYtelse = folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_KunYtelseDto;

export type VurderMottarYtelse = folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_VurderMottarYtelseDto;

export type ATFLSammeOrgAndel = folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_ATogFLISammeOrganisasjonDto;

export type FaktaOmBeregning = folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_FaktaOmBeregningDto;
