import type { tjenester_behandling_beregningsresultat_dto_BeregningsresultatEngangsstønadDto } from './apiDtoGenerert.ts';

export type BeregningsresultatEs = tjenester_behandling_beregningsresultat_dto_BeregningsresultatEngangsstønadDto;
