import type {
  tjenester_behandling_beregningsresultat_dto_BeregningsresultatMedUttaksplanDto,
  tjenester_behandling_beregningsresultat_dto_BeregningsresultatPeriodeAndelDto,
  tjenester_behandling_beregningsresultat_dto_BeregningsresultatPeriodeDto,
} from './fpsak.gen';

export type BeregningsresultatPeriodeAndel =
  tjenester_behandling_beregningsresultat_dto_BeregningsresultatPeriodeAndelDto;

export type BeregningsresultatPeriode = tjenester_behandling_beregningsresultat_dto_BeregningsresultatPeriodeDto;

export type BeregningsresultatDagytelse =
  tjenester_behandling_beregningsresultat_dto_BeregningsresultatMedUttaksplanDto;
