import type {
  folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_fp_BesteberegninggrunnlagDto,
  folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_fp_BesteberegningInntektDto,
  folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_fp_BesteberegningMånedGrunnlagDto,
} from './apiDtoGenerert';

export type Månedsgrunnlag =
  folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_fp_BesteberegningMånedGrunnlagDto;

export type BesteberegningInntekt =
  folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_fp_BesteberegningInntektDto;

export type Besteberegninggrunnlag =
  folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_fp_BesteberegninggrunnlagDto;
