import type {
  tjenester_behandling_uttak_dokumentasjon_DokumentasjonVurderingBehovDto,
  tjenester_behandling_uttak_dokumentasjon_DokumentasjonVurderingBehovDto_AktivitetskravGrunnlagArbeid,
} from './apiDtoGenerert.ts';

export type DokumentasjonVurderingBehov = tjenester_behandling_uttak_dokumentasjon_DokumentasjonVurderingBehovDto;

export type AktivitetskravGrunnlagArbeid =
  tjenester_behandling_uttak_dokumentasjon_DokumentasjonVurderingBehovDto_AktivitetskravGrunnlagArbeid;
