import type {
  foreldrepenger_domene_uttak_fakta_uttak_DokumentasjonVurderingBehov_Behov_Årsak,
  foreldrepenger_domene_uttak_fakta_uttak_DokumentasjonVurderingBehov_Behov_Type,
  tjenester_behandling_uttak_dokumentasjon_DokumentasjonVurderingBehovDto,
  tjenester_behandling_uttak_dokumentasjon_DokumentasjonVurderingBehovDto_AktivitetskravGrunnlagArbeid,
  tjenester_behandling_uttak_dokumentasjon_DokumentasjonVurderingBehovDto_Vurdering,
} from './apiDtoGenerert';

export type DokumentasjonVurderingBehov = tjenester_behandling_uttak_dokumentasjon_DokumentasjonVurderingBehovDto;

export type AktivitetskravGrunnlagArbeid =
  tjenester_behandling_uttak_dokumentasjon_DokumentasjonVurderingBehovDto_AktivitetskravGrunnlagArbeid;

export type UttakType = foreldrepenger_domene_uttak_fakta_uttak_DokumentasjonVurderingBehov_Behov_Type;

export type UttakVurdering = tjenester_behandling_uttak_dokumentasjon_DokumentasjonVurderingBehovDto_Vurdering;

export type UttakÅrsak = foreldrepenger_domene_uttak_fakta_uttak_DokumentasjonVurderingBehov_Behov_Årsak;
