import type {
  tjenester_familiehendelse_FamiliehendelseRestTjeneste_AdopsjonFamilieHendelseDto,
  tjenester_familiehendelse_FamiliehendelseRestTjeneste_FamilieHendelseDto,
  tjenester_familiehendelse_FamiliehendelseRestTjeneste_FødselTerminFamilieHendelseDto,
} from './fpsak.gen';

export type FamilieHendelse = tjenester_familiehendelse_FamiliehendelseRestTjeneste_FamilieHendelseDto;

export type FødselTerminFamilieHendelse =
  tjenester_familiehendelse_FamiliehendelseRestTjeneste_FødselTerminFamilieHendelseDto;

export type AdopsjonFamilieHendelse = tjenester_familiehendelse_FamiliehendelseRestTjeneste_AdopsjonFamilieHendelseDto;
