import type { foreldrepenger_behandlingslager_behandling_familiehendelse_FamilieHendelseType } from './apiDtoGenerert';

export type FamilieHendelseType = foreldrepenger_behandlingslager_behandling_familiehendelse_FamilieHendelseType;
