import type { foreldrepenger_behandlingslager_risikoklassifisering_FaresignalVurdering } from './apiDtoGenerert';

export type FaresignalVurdering = foreldrepenger_behandlingslager_risikoklassifisering_FaresignalVurdering;
