import type {
  tjenester_behandling_beregningsresultat_dto_FeriepengegrunnlagAndelDto,
  tjenester_behandling_beregningsresultat_dto_FeriepengegrunnlagDto,
} from './apiDtoGenerert';

export type FeriepengegrunnlagAndel = tjenester_behandling_beregningsresultat_dto_FeriepengegrunnlagAndelDto;

export type Feriepengegrunnlag = tjenester_behandling_beregningsresultat_dto_FeriepengegrunnlagDto;
