import type {
  tjenester_behandling_svp_SvpArbeidsforholdDto,
  tjenester_behandling_svp_SvpAvklartOppholdPeriodeDto,
  tjenester_behandling_svp_SvpTilretteleggingDatoDto,
  tjenester_behandling_svp_SvpTilretteleggingDto,
  tjenester_behandling_svp_VelferdspermisjonDto,
} from './apiDtoGenerert.ts';

export type Permisjon = tjenester_behandling_svp_VelferdspermisjonDto;

export type ArbeidsforholdTilretteleggingDato = tjenester_behandling_svp_SvpTilretteleggingDatoDto;

export type SvpAvklartOppholdPeriode = tjenester_behandling_svp_SvpAvklartOppholdPeriodeDto;

export type ArbeidsforholdFodselOgTilrettelegging = tjenester_behandling_svp_SvpArbeidsforholdDto;

export type FodselOgTilrettelegging = tjenester_behandling_svp_SvpTilretteleggingDto;
