import type { foreldrepenger_behandlingslager_behandling_ytelsefordeling_periode_FordelingPeriodeKilde } from './apiDtoGenerert';

export type FordelingPeriodeKilde =
  foreldrepenger_behandlingslager_behandling_ytelsefordeling_periode_FordelingPeriodeKilde;
