import type { foreldrepenger_behandlingslager_behandling_ytelsefordeling_periode_FordelingPeriodeKilde } from './fpsak.gen';

export type FordelingPeriodeKilde =
  foreldrepenger_behandlingslager_behandling_ytelsefordeling_periode_FordelingPeriodeKilde;
