import type { foreldrepenger_behandlingslager_behandling_ytelsefordeling_periode_FordelingPeriodeKilde } from '@navikt/fp-types';

export type FordelingPeriodeKilde =
  foreldrepenger_behandlingslager_behandling_ytelsefordeling_periode_FordelingPeriodeKilde;
