import type {
  tjenester_behandling_fødsel_dto_FødselDto,
  tjenester_behandling_fødsel_dto_FødselDto_BarnHendelseData,
  tjenester_behandling_fødsel_dto_FødselDto_Gjeldende,
  tjenester_behandling_fødsel_dto_FødselDto_Gjeldende_GjeldendeBarn,
  tjenester_behandling_fødsel_dto_FødselDto_Register,
  tjenester_behandling_fødsel_dto_FødselDto_Søknad,
} from './apiDtoGenerert.ts';

export type BarnHendelseData = tjenester_behandling_fødsel_dto_FødselDto_BarnHendelseData;

export type Fødsel = tjenester_behandling_fødsel_dto_FødselDto;

export type FødselSøknad = tjenester_behandling_fødsel_dto_FødselDto_Søknad;

export type FødselRegister = tjenester_behandling_fødsel_dto_FødselDto_Register;

export type FødselGjeldende = tjenester_behandling_fødsel_dto_FødselDto_Gjeldende;

export type FødselDtoGjeldendeBarn = tjenester_behandling_fødsel_dto_FødselDto_Gjeldende_GjeldendeBarn;
