import type {
  foreldrepenger_behandlingslager_behandling_historikk_HistorikkAktør,
  tjenester_behandling_historikk_HistorikkInnslagDokumentLinkDto,
  tjenester_behandling_historikk_HistorikkinnslagDto,
} from './apiDtoGenerert';

export type Historikkinnslag = tjenester_behandling_historikk_HistorikkinnslagDto;

export type HistorikkInnslagDokumentLink = tjenester_behandling_historikk_HistorikkInnslagDokumentLinkDto;

export type HistorikkAktør = foreldrepenger_behandlingslager_behandling_historikk_HistorikkAktør;
