import type { foreldrepenger_domene_arbeidInntektsmelding_ManglendeOpplysningerVurderingDto } from './apiDtoGenerert.ts';

export type ManglendeInntektsmeldingVurdering =
  foreldrepenger_domene_arbeidInntektsmelding_ManglendeOpplysningerVurderingDto;
