import type { foreldrepenger_behandlingslager_behandling_medlemskap_MedlemskapManuellVurderingType } from './apiDtoGenerert';

export type MedlemskapManuellVurderingType =
  foreldrepenger_behandlingslager_behandling_medlemskap_MedlemskapManuellVurderingType;
