import type {
  foreldrepenger_behandlingslager_aktør_OppholdstillatelseType,
  foreldrepenger_behandlingslager_behandling_medlemskap_MedlemskapManuellVurderingType,
  foreldrepenger_behandlingslager_behandling_medlemskap_MedlemskapType,
  foreldrepenger_inngangsvilkaar_medlemskap_MedlemskapAvvik,
  tjenester_behandling_medlem_MedlemskapDto,
  tjenester_behandling_medlem_MedlemskapDto_LegacyManuellBehandling,
  tjenester_behandling_medlem_MedlemskapDto_LegacyManuellBehandling_MedlemPeriode,
  tjenester_behandling_medlem_MedlemskapDto_ManuellBehandlingResultat,
  tjenester_behandling_medlem_MedlemskapDto_MedlemskapPeriode,
  tjenester_behandling_medlem_MedlemskapDto_Oppholdstillatelse,
  tjenester_behandling_medlem_MedlemskapDto_Personstatus,
  tjenester_behandling_medlem_MedlemskapDto_Region,
  tjenester_behandling_medlem_MedlemskapDto_Utlandsopphold,
} from './apiDtoGenerert';

export type RegionPeriode = tjenester_behandling_medlem_MedlemskapDto_Region;

export type PersonstatusPeriode = tjenester_behandling_medlem_MedlemskapDto_Personstatus;

export type Oppholdstillatelse = tjenester_behandling_medlem_MedlemskapDto_Oppholdstillatelse;

export type OppholdstillatelseType = foreldrepenger_behandlingslager_aktør_OppholdstillatelseType;

export type MedlemskapPeriode = tjenester_behandling_medlem_MedlemskapDto_MedlemskapPeriode;

export type MedlemskapType = foreldrepenger_behandlingslager_behandling_medlemskap_MedlemskapType;

export type MedlemskapAvvik = foreldrepenger_inngangsvilkaar_medlemskap_MedlemskapAvvik;

export type LegacyMedlemPeriode = tjenester_behandling_medlem_MedlemskapDto_LegacyManuellBehandling_MedlemPeriode;

export type MedlemskapManuellVurderingType =
  foreldrepenger_behandlingslager_behandling_medlemskap_MedlemskapManuellVurderingType;

export type LegacyManuellMedlemskapsBehandling = tjenester_behandling_medlem_MedlemskapDto_LegacyManuellBehandling;

export type ManuellBehandlingResultat = tjenester_behandling_medlem_MedlemskapDto_ManuellBehandlingResultat;

export type Medlemskap = tjenester_behandling_medlem_MedlemskapDto;

export type UtlandsoppholdPeriode = tjenester_behandling_medlem_MedlemskapDto_Utlandsopphold;
