import type { foreldrepenger_behandlingslager_behandling_familiehendelse_OmsorgsovertakelseVilkårType } from './apiDtoGenerert';

export type OmsorgsovertakelseVilkårType =
  foreldrepenger_behandlingslager_behandling_familiehendelse_OmsorgsovertakelseVilkårType;
