import type { foreldrepenger_behandlingslager_behandling_familiehendelse_OmsorgsovertakelseVilkårType } from './fpsak.gen';

export type OmsorgsovertakelseVilkårType =
  foreldrepenger_behandlingslager_behandling_familiehendelse_OmsorgsovertakelseVilkårType;
