import type { foreldrepenger_behandlingslager_behandling_ytelsefordeling_årsak_OppholdÅrsak } from '@navikt/fp-types';

export type OppholdÅrsakType = foreldrepenger_behandlingslager_behandling_ytelsefordeling_årsak_OppholdÅrsak;
