import type { foreldrepenger_behandlingslager_behandling_opptjening_OpptjeningAktivitetType } from '@navikt/fp-types';

export type OpptjeningAktivitetType = foreldrepenger_behandlingslager_behandling_opptjening_OpptjeningAktivitetType;
