import type {
  foreldrepenger_domene_opptjening_dto_FastsattOpptjeningDto,
  foreldrepenger_domene_opptjening_dto_FastsattOpptjeningDto_FastsattOpptjeningAktivitetDto,
  foreldrepenger_domene_opptjening_dto_FerdiglignetNæringDto,
  foreldrepenger_domene_opptjening_dto_OpptjeningAktivitetDto,
  foreldrepenger_domene_opptjening_dto_OpptjeningDto,
} from './apiDtoGenerert';

export type OpptjeningAktivitet = foreldrepenger_domene_opptjening_dto_OpptjeningAktivitetDto;

export type FastsattOpptjeningAktivitet =
  foreldrepenger_domene_opptjening_dto_FastsattOpptjeningDto_FastsattOpptjeningAktivitetDto;

export type FastsattOpptjening = foreldrepenger_domene_opptjening_dto_FastsattOpptjeningDto;

export type FerdiglignetNæring = foreldrepenger_domene_opptjening_dto_FerdiglignetNæringDto;

export type Opptjening = foreldrepenger_domene_opptjening_dto_OpptjeningDto;
