import type { foreldrepenger_behandlingslager_behandling_opptjening_OpptjeningAktivitetType } from './apiDtoGenerert';

export type OpptjeningAktivitetType = foreldrepenger_behandlingslager_behandling_opptjening_OpptjeningAktivitetType;
