import type { foreldrepenger_behandlingslager_behandling_ytelsefordeling_årsak_OverføringÅrsak } from '@navikt/fp-types';

export type OverføringÅrsak = foreldrepenger_behandlingslager_behandling_ytelsefordeling_årsak_OverføringÅrsak;
