import type { foreldrepenger_domene_iay_modell_kodeverk_PermisjonsbeskrivelseType } from './apiDtoGenerert';

export type PermisjonsbeskrivelseType = foreldrepenger_domene_iay_modell_kodeverk_PermisjonsbeskrivelseType;
