import type { foreldrepenger_behandlingslager_behandling_personopplysning_RelasjonsRolleType } from '@navikt/fp-types';

export type RelasjonsRolleType = foreldrepenger_behandlingslager_behandling_personopplysning_RelasjonsRolleType;
