import type { foreldrepenger_behandlingslager_behandling_personopplysning_RelasjonsRolleType } from './fpsak.gen';

export type RelasjonsRolleType = foreldrepenger_behandlingslager_behandling_personopplysning_RelasjonsRolleType;
