import type { foreldrepenger_behandlingslager_behandling_ytelsefordeling_Rettighetstype } from './apiDtoGenerert';

export type Rettighetstype = foreldrepenger_behandlingslager_behandling_ytelsefordeling_Rettighetstype;
