import type {
  foreldrepenger_kontrakter_simulering_resultat_v1_PeriodeDto,
  foreldrepenger_kontrakter_simulering_resultat_v1_SimuleringDto,
  foreldrepenger_kontrakter_simulering_resultat_v1_SimuleringDto_DetaljertSimuleringResultatDto,
  foreldrepenger_kontrakter_simulering_resultat_v1_SimuleringDto_SimuleringForMottakerDto,
  foreldrepenger_kontrakter_simulering_resultat_v1_SimuleringDto_SimuleringResultatPerFagområdeDto,
  foreldrepenger_kontrakter_simulering_resultat_v1_SimuleringDto_SimuleringResultatRadDto,
} from './fpsak.gen';

export type SimuleringPeriode = foreldrepenger_kontrakter_simulering_resultat_v1_PeriodeDto;

export type SimuleringResultatRad =
  foreldrepenger_kontrakter_simulering_resultat_v1_SimuleringDto_SimuleringResultatRadDto;

export type SimuleringResultatPerFagområde =
  foreldrepenger_kontrakter_simulering_resultat_v1_SimuleringDto_SimuleringResultatPerFagområdeDto;

export type Mottaker = foreldrepenger_kontrakter_simulering_resultat_v1_SimuleringDto_SimuleringForMottakerDto;

export type DetaljertSimuleringResultat =
  foreldrepenger_kontrakter_simulering_resultat_v1_SimuleringDto_DetaljertSimuleringResultatDto;

export type SimuleringResultat = foreldrepenger_kontrakter_simulering_resultat_v1_SimuleringDto;
