import type { foreldrepenger_behandlingslager_behandling_personopplysning_SivilstandType } from './apiDtoGenerert';

export type SivilstandType = foreldrepenger_behandlingslager_behandling_personopplysning_SivilstandType;
