import type {
  tjenester_behandling_vedtak_dto_TotrinnskontrollAksjonspunkterDto,
  tjenester_behandling_vedtak_dto_TotrinnskontrollAktivitetDto,
} from './apiDtoGenerert.ts';

export type OpptjeningAktiviteter = tjenester_behandling_vedtak_dto_TotrinnskontrollAktivitetDto;

export type TotrinnskontrollAksjonspunkt = tjenester_behandling_vedtak_dto_TotrinnskontrollAksjonspunkterDto;
