import type { foreldrepenger_behandlingslager_behandling_ytelsefordeling_årsak_UtsettelseÅrsak } from './fpsak.gen';

export type UtsettelseÅrsak = foreldrepenger_behandlingslager_behandling_ytelsefordeling_årsak_UtsettelseÅrsak;
