import type { foreldrepenger_behandlingslager_behandling_ytelsefordeling_periode_UttakPeriodeType } from './fpsak.gen';

export type UttakPeriodeType = foreldrepenger_behandlingslager_behandling_ytelsefordeling_periode_UttakPeriodeType;
