import type {
  tjenester_behandling_uttak_dto_UttakResultatPeriodeAktivitetDto,
  tjenester_behandling_uttak_dto_UttakResultatPeriodeDto,
  tjenester_behandling_uttak_dto_UttakResultatPerioderDto,
  tjenester_behandling_uttak_dto_UttakResultatPerioderDto_FilterDto,
} from './apiDtoGenerert.ts';

export type PeriodeSokerAktivitet = tjenester_behandling_uttak_dto_UttakResultatPeriodeAktivitetDto;

export type PeriodeSoker = tjenester_behandling_uttak_dto_UttakResultatPeriodeDto;

export type AarsakFilter = tjenester_behandling_uttak_dto_UttakResultatPerioderDto_FilterDto;

export type Uttaksresultat = tjenester_behandling_uttak_dto_UttakResultatPerioderDto;
