export type BehandlingResultatTypeFpTilbake =
  | 'IKKE_FASTSATT'
  | 'FASTSATT'
  | 'HENLAGT_FEILOPPRETTET'
  | 'HENLAGT_FEILOPPRETTET_MED_BREV'
  | 'HENLAGT_FEILOPPRETTET_UTEN_BREV'
  | 'HENLAGT_KRAVGRUNNLAG_NULLSTILT'
  | 'HENLAGT_TEKNISK_VEDLIKEHOLD'
  | 'HENLAGT'
  | 'INGEN_TILBAKEBETALING'
  | 'DELVIS_TILBAKEBETALING'
  | 'FULL_TILBAKEBETALING';
