export type VenteÅrsakTypeFpTilbake =
  | 'VENT_PÅ_BRUKERTILBAKEMELDING'
  | 'VENT_PÅ_TILBAKEKREVINGSGRUNNLAG'
  | 'AVV_DOK'
  | 'UTV_TIL_FRIST'
  | 'ENDRE_TILKJENT_YTELSE'
  | 'VENT_PÅ_MULIG_MOTREGNING';
