apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fp-frontend-azure
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  image: ghcr.io/navikt/fp-frontend-azure:0.42
  port: 9090
  ingresses:
    - "https://fpsak.dev.intern.nav.no"
  liveness:
    path: /isAlive
    initialDelay: 5
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /isReady
    initialDelay: 5
    timeout: 1
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 64Mi
    requests:
      cpu: 200m
      memory: 32Mi
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  webproxy: true
  env:
    - name: PORT
      value: "9090"
    - name: REDIS_HOST
      value: "fpsak-redis.teamforeldrepenger.svc.nais.local"
    - name: REDIS_PORT
      value: "6379"
    - name: DOWNSTREAM_API_URL
      value: "https://fpsak.dev.adeo.no"
    - name: DOWNSTREAM_API_PATH
      value: ""
    - name: DOWNSTREAM_API_CLIENT_ID
      value: "dev-fss.teamforeldrepenger.fpsak"
    - name: AZURE_APP_LOGOUT_REDIRECT_URL
      value: https://fpsak.dev.intern.nav.no/
    - name: AZURE_APP_REDIRECT_URL
      value: https://fpsak.dev.intern.nav.no/oauth2/callback
    - name: SESSION_KEY
      value: sdfldfsdfflewrjsdjsldfl
  envFrom:
    - secret: redis-password
#  accessPolicy:
#    outbound:
#      rules:
#        - application: fpsak-redis

