apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fp-frontend
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - "https://fpsak.intern.nav.no"
  liveness:
    path: /isAlive
    initialDelay: 10
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /isReady
    initialDelay: 10
    timeout: 1
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 64Mi
    requests:
      cpu: 200m
      memory: 32Mi
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
        groups:
          - id: "73107205-17ec-4a07-a56e-e0a8542f90c9" # saksbehandlere
          - id: "237ec744-da1f-455b-a794-b2d59c7ce7ee" # beslutter
          - id: "77f05833-ebfd-45fb-8be7-88eca8e7418f" # veileder
          - id: "1a59da27-4c55-4a9d-8480-6abd1a856cd2" # oppgavestyrer
          - id: "8200240e-d76d-4d48-a655-728d1d8c3641" # manuell overstyrer
      singlePageApplication: true
    sidecar:
      enabled: true
      autoLogin: true
  accessPolicy:
    outbound:
      external:
        - host: fpsak-api.prod-fss-pub.nais.io
        - host: fplos.prod-fss-pub.nais.io
        - host: fpformidling.prod-fss-pub.nais.io
        - host: fpoppdrag.prod-fss-pub.nais.io
        - host: fptilbake.prod-fss-pub.nais.io
  env:
    - name: HOST
      value: "https://fpsak.intern.nav.no"
    - name: PORT
      value: "8080"
    - name: CORS_ALLOWED_HEADERS
      value: "Referer, Origin, Content-Type, Accept, X-Requested-With, cache-control, x_Nav-CallId, pragma, expires, X-Forwarded-Proto"
    - name: CORS_EXPOSED_HEADERS
      value: "Location"
    - name: CORS_ALLOWED_METHODS
      value: "GET, POST"
    - name: PROXY_CONFIG
      value: '{"apis":[{"path":"/fpsak/api","url":"https://fpsak-api.prod-fss-pub.nais.io","scopes":"api://prod-fss.teamforeldrepenger.fpsak/.default"},
                       {"path":"/fptilbake/api","url":"https://fptilbake.prod-fss-pub.nais.io","scopes":"api://prod-fss.teamforeldrepenger.fptilbake/.default"},
                       {"path":"/fplos/api","url":"https://fplos.prod-fss-pub.nais.io","scopes":"api://prod-fss.teamforeldrepenger.fplos/.default"},
                       {"path":"/fpoppdrag/api","url":"https://fpoppdrag.prod-fss-pub.nais.io","scopes":"api://prod-fss.teamforeldrepenger.fpoppdrag/.default"},
                       {"path":"/fpformidling/api","url":"https://fpformidling.prod-fss-pub.nais.io","scopes":"api://prod-fss.teamforeldrepenger.fpformidling/.default"}
              ]}'

