apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fp-frontend-azure
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  image: ghcr.io/navikt/fp-frontend-azure:0.75
  port: 9090
  ingresses:
    - "https://fpsak.dev.intern.nav.no"
  liveness:
    path: /isAlive
    initialDelay: 5
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /isReady
    initialDelay: 5
    timeout: 1
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 64Mi
    requests:
      cpu: 200m
      memory: 32Mi
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  webproxy: true
  env:
    - name: HOST
      value: "https://fpsak.dev.intern.nav.no"
    - name: PORT
      value: "9090"
    - name: REDIS_HOST
      value: "fpsak-redis.teamforeldrepenger.svc.nais.local"
    - name: REDIS_PORT
      value: "6379"
    - name: CORS_ALLOWED_HEADERS
      value: "Referer, Origin, Content-Type, Accept, X-Requested-With, cache-control, x_Nav-CallId, pragma, expires"
    - name: CORS_EXPOSED_HEADERS
      value: "Location"
    - name: CORS_ALLOWED_METHODS
      value: "GET, POST"
    - name: AZURE_APP_LOGOUT_REDIRECT_URL
      value: https://familie.nav.no/
    - name: AZURE_APP_REDIRECT_URL
      value: https://fpsak.dev.intern.nav.no/oauth2/callback
    - name: PROXY_CONFIG
      value: '{"apis":[{"path":"/fpsak/api","url":"http://fpsak","scopes":"api://dev-fss.teamforeldrepenger.fpsak/.default"},
                       {"path":"/fptilbake/api","url":"http://fptilbake","scopes":"api://dev-fss.teamforeldrepenger.fptilbake/.default"},
                       {"path":"/fplos/api","url":"http://fplos","scopes":"api://dev-fss.teamforeldrepenger.fplos/.default"},
                       {"path":"/fpoppdrag/api","url":"http://fpoppdrag","scopes":"api://dev-fss.teamforeldrepenger.fpoppdrag/.default"},
                       {"path":"/fpformidling/api","url":"http://fpformidling","scopes":"api://dev-fss.teamforeldrepenger.fpformidling/.default"}
              ]}'
  envFrom:
    - secret: redis-password
    - secret: fp-frontend-secrets # cookie sigh and verify
#  accessPolicy:
#    outbound:
#      rules:
#        - application: fpsak-redis

