apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: teamforeldrepenger
  name: fpsak-redis
  namespace: default
spec:
  image: redis:4.0-alpine
  port: 6379
  sessionAffinity: ClientIP
  team: teamforeldrepenger
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  leaderElection: false
  preStopHookPath: ""
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  webproxy: false
  vault:
    enabled: false
