import React from 'react';
import { StoryFn } from '@storybook/react';
import { action } from '@storybook/addon-actions';

import {
  Behandling,
  FamilieHendelseSamling,
  Personoversikt,
  Soknad,
  UttaksresultatPeriode,
  UttakStonadskontoer,
  Aksjonspunkt,
  Fagsak,
} from '@navikt/fp-types';
import { alleKodeverk } from '@navikt/fp-storybook-utils';
import {
  utsettelseArsakCodes,
  AksjonspunktCode,
  aksjonspunktType,
  aksjonspunktStatus as AksjonspunktStatus,
  navBrukerKjonn as NavBrukerKjonn,
  relasjonsRolleType,
} from '@navikt/fp-kodeverk';
import { ProsessAksjonspunkt } from '@navikt/fp-types-avklar-aksjonspunkter';

import UttakProsessIndex from './UttakProsessIndex';

const åpentAksjonspunkt = [
  {
    definisjon: AksjonspunktCode.FASTSETT_UTTAKPERIODER,
    status: AksjonspunktStatus.OPPRETTET,
    toTrinnsBehandling: true,
    aksjonspunktType: aksjonspunktType.MANUELL,
    kanLoses: true,
  },
];

const familiehendelse = {
  gjeldende: {
    skjaringstidspunkt: '2019-11-04',
    avklartBarn: [
      {
        fodselsdato: '2019-11-04',
      },
    ],
  },
} as FamilieHendelseSamling;

const fagsak = {
  relasjonsRolleType: relasjonsRolleType.MOR,
  annenpartBehandling: {
    relasjonsRolleType: relasjonsRolleType.FAR,
  },
} as Fagsak;

const behandling = {
  uuid: '1',
  versjon: 1,
  type: 'BT-002',
  behandlingsresultat: {
    skjæringstidspunkt: {
      dato: '2019-10-14',
    },
  },
  status: 'UTRED',
  sprakkode: '-',
} as Behandling;

const uttakStonadskontoer = {
  tapteDagerFpff: 1,
  stonadskontoer: {
    FEDREKVOTE: {
      stonadskontotype: 'FEDREKVOTE',
      maxDager: 75,
      saldo: 50,
      aktivitetSaldoDtoList: [
        {
          aktivitetIdentifikator: {
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            arbeidsgiverReferanse: '910909088',
          },
          saldo: 50,
        },
      ],
      gyldigForbruk: true,
    },
    MØDREKVOTE: {
      stonadskontotype: 'MØDREKVOTE',
      maxDager: 75,
      saldo: 35,
      aktivitetSaldoDtoList: [
        {
          aktivitetIdentifikator: {
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            arbeidsgiverReferanse: '910909088',
          },
          saldo: 35,
        },
      ],
      gyldigForbruk: true,
    },
    FELLESPERIODE: {
      stonadskontotype: 'FELLESPERIODE',
      maxDager: 80,
      saldo: 80,
      aktivitetSaldoDtoList: [
        {
          aktivitetIdentifikator: {
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            arbeidsgiverReferanse: '910909088',
          },
          saldo: 80,
        },
      ],
      gyldigForbruk: true,
    },
    FORELDREPENGER_FØR_FØDSEL: {
      stonadskontotype: 'FORELDREPENGER_FØR_FØDSEL',
      maxDager: 15,
      saldo: 0,
      aktivitetSaldoDtoList: [
        {
          aktivitetIdentifikator: {
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            arbeidsgiverReferanse: '910909088',
          },
          saldo: 0,
        },
      ],
      gyldigForbruk: true,
    },
  },
} as UttakStonadskontoer;

const soknad = {
  soknadType: 'ST-001',
  mottattDato: '2019-11-18',
  fodselsdatoer: {
    1: '2019-11-04',
  } as { [key: number]: string },
  søknadsfrist: {
    mottattDato: '2019-11-18',
    utledetSøknadsfrist: '2020-01-31',
    søknadsperiodeStart: '2019-10-14',
    søknadsperiodeSlutt: '2020-02-02',
    dagerOversittetFrist: -74,
  },
} as Soknad;

const ytelsefordeling = {
  annenforelderHarRettDto: {
    avklarAnnenforelderMottarUføretrygd: false,
  },
  rettigheterAnnenforelder: {
    skalAvklareAnnenforelderUføretrygd: false,
    skalAvklareAnnenForelderRettEØS: false,
  },
  endringsdato: '2019-10-14',
  gjeldendeDekningsgrad: 100,
  førsteUttaksdato: '2019-10-14',
};

const arbeidsgiverOpplysningerPerId = {
  342352362: {
    referanse: '342352362',
    identifikator: '342352362',
    navn: 'Lagt til av saksbehandler',
    fødselsdato: undefined,
    erPrivatPerson: false,
  },
  910909088: {
    referanse: '910909088',
    identifikator: '910909088',
    navn: 'BEDRIFT AS',
    fødselsdato: undefined,
    erPrivatPerson: false,
  },
  994884174: {
    referanse: '994884174',
    identifikator: '994884174',
    navn: 'NAV',
    fødselsdato: undefined,
    erPrivatPerson: false,
  },
};

export default {
  title: 'prosess/prosess-uttak',
  component: UttakProsessIndex,
};

const Template: StoryFn<{
  submitCallback?: (aksjonspunktData: ProsessAksjonspunkt | ProsessAksjonspunkt[]) => Promise<void>;
  stønadskontoer?: UttakStonadskontoer;
  kanOverstyre?: boolean;
  isReadOnly?: boolean;
  uttaksresultatPerioder: UttaksresultatPeriode;
  aksjonspunkter?: Aksjonspunkt[];
  brukerKjønn?: string;
}> = ({
  submitCallback = action('button-click') as (data: any) => Promise<any>,
  stønadskontoer = uttakStonadskontoer,
  uttaksresultatPerioder,
  kanOverstyre = false,
  isReadOnly = false,
  aksjonspunkter = [],
  brukerKjønn = NavBrukerKjonn.KVINNE,
}) => (
  <UttakProsessIndex
    behandling={behandling}
    uttaksresultatPerioder={uttaksresultatPerioder}
    uttakStonadskontoer={stønadskontoer}
    aksjonspunkter={aksjonspunkter}
    familiehendelse={familiehendelse}
    soknad={soknad}
    personoversikt={
      {
        bruker: {
          kjønn: brukerKjønn,
        },
      } as Personoversikt
    }
    ytelsefordeling={ytelsefordeling}
    alleKodeverk={alleKodeverk as any}
    kanOverstyre={kanOverstyre}
    submitCallback={submitCallback}
    isReadOnly={isReadOnly}
    readOnlySubmitButton={false}
    oppdaterStønadskontoer={v => {
      action('button-click')(v);
      return Promise.resolve(stønadskontoer);
    }}
    isAksjonspunktOpen
    status="test"
    vilkar={[]}
    arbeidsgiverOpplysningerPerId={arbeidsgiverOpplysningerPerId}
    alleMerknaderFraBeslutter={{}}
    setFormData={() => undefined}
    fagsak={fagsak}
  />
);

export const AksjonspunktDerValgtStønadskontoIkkeFinnes = Template.bind({});
AksjonspunktDerValgtStønadskontoIkkeFinnes.args = {
  aksjonspunkter: åpentAksjonspunkt,
  uttaksresultatPerioder: {
    perioderSøker: [
      {
        fom: '2022-10-20',
        tom: '2022-11-09',
        aktiviteter: [
          {
            stønadskontoType: 'FORELDREPENGER',
            prosentArbeid: 0,
            arbeidsforholdId: 'de6cb16e-9520-418c-a438-aa781b0833c2',
            eksternArbeidsforholdId: 'ARB001-002',
            arbeidsgiverReferanse: '994884174',
            utbetalingsgrad: undefined,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 15.0,
          },
          {
            stønadskontoType: 'FORELDREPENGER',
            prosentArbeid: 0,
            arbeidsforholdId: 'de6cb16e-9520-418c-a438-aa781b0833c1',
            eksternArbeidsforholdId: 'ARB001-001',
            arbeidsgiverReferanse: '910909088',
            utbetalingsgrad: undefined,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 14.0,
          },
        ],
        periodeResultatType: 'MANUELL_BEHANDLING',
        begrunnelse: undefined,
        periodeResultatÅrsak: '4002',
        manuellBehandlingÅrsak: '5002',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: false,
        periodeType: 'FORELDREPENGER',
        utsettelseType: '-',
        oppholdÅrsak: '-',
        mottattDato: '2023-01-05',
        gradertAktivitet: undefined,
      },
      {
        fom: '2022-11-10',
        tom: '2022-12-21',
        aktiviteter: [
          {
            stønadskontoType: 'MØDREKVOTE',
            prosentArbeid: 0,
            arbeidsforholdId: 'de6cb16e-9520-418c-a438-aa781b0833c2',
            eksternArbeidsforholdId: 'ARB001-002',
            arbeidsgiverReferanse: '994884174',
            utbetalingsgrad: 0,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 30.0,
          },
        ],
        periodeResultatType: 'AVSLÅTT',
        begrunnelse: undefined,
        periodeResultatÅrsak: '4103',
        manuellBehandlingÅrsak: '-',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: false,
        periodeType: 'FORELDREPENGER',
        utsettelseType: '-',
        oppholdÅrsak: '-',
        mottattDato: undefined,
        gradertAktivitet: undefined,
      },
    ],
    perioderAnnenpart: [],
    annenForelderHarRett: true,
    aleneomsorg: false,
    årsakFilter: { kreverSammenhengendeUttak: false, kreverSammenhengendeUttakTom: '2021-09-30', utenMinsterett: false, søkerErMor: true },
  },
};

export const PeriodeMedGraderingUtenAksjonspunkt = Template.bind({});
PeriodeMedGraderingUtenAksjonspunkt.args = {
  kanOverstyre: true,
  uttaksresultatPerioder: {
    perioderSøker: [
      {
        fom: '2019-10-11',
        tom: '2019-10-31',
        aktiviteter: [
          {
            stønadskontoType: 'FORELDREPENGER_FØR_FØDSEL',
            prosentArbeid: 0,
            arbeidsforholdId: 'efaf22ef-76aa-4576-8c96-92bd31af8815',
            eksternArbeidsforholdId: 'ARB001-001',
            arbeidsgiverReferanse: '910909088',
            utbetalingsgrad: 100,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 15.0,
          },
        ],
        periodeResultatType: 'INNVILGET',
        begrunnelse: undefined,
        periodeResultatÅrsak: '2006',
        manuellBehandlingÅrsak: '-',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: false,
        periodeType: 'FORELDREPENGER_FØR_FØDSEL',
        utsettelseType: '-',
        oppholdÅrsak: '-',
        mottattDato: '2019-11-01',
        gradertAktivitet: undefined,
      },
      {
        fom: '2019-11-01',
        tom: '2019-12-12',
        aktiviteter: [
          {
            stønadskontoType: 'MØDREKVOTE',
            prosentArbeid: 0,
            arbeidsforholdId: 'efaf22ef-76aa-4576-8c96-92bd31af8815',
            eksternArbeidsforholdId: 'ARB001-001',
            arbeidsgiverReferanse: '910909088',
            utbetalingsgrad: 100,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 30.0,
          },
        ],
        periodeResultatType: 'INNVILGET',
        begrunnelse: undefined,
        periodeResultatÅrsak: '2003',
        manuellBehandlingÅrsak: '-',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: false,
        periodeType: 'MØDREKVOTE',
        utsettelseType: '-',
        oppholdÅrsak: '-',
        mottattDato: '2019-11-01',
        gradertAktivitet: undefined,
      },
      {
        fom: '2019-12-13',
        tom: '2020-01-23',
        aktiviteter: [
          {
            stønadskontoType: 'MØDREKVOTE',
            prosentArbeid: 50,
            arbeidsforholdId: 'efaf22ef-76aa-4576-8c96-92bd31af8815',
            eksternArbeidsforholdId: 'ARB001-001',
            arbeidsgiverReferanse: '910909088',
            utbetalingsgrad: 50,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: true,
            trekkdagerDesimaler: 15.0,
          },
        ],
        periodeResultatType: 'INNVILGET',
        begrunnelse: undefined,
        periodeResultatÅrsak: '2031',
        manuellBehandlingÅrsak: '-',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: true,
        periodeType: 'MØDREKVOTE',
        utsettelseType: '-',
        oppholdÅrsak: '-',
        mottattDato: '2019-11-01',
        gradertAktivitet: {
          stønadskontoType: 'MØDREKVOTE',
          prosentArbeid: 50,
          arbeidsforholdId: 'efaf22ef-76aa-4576-8c96-92bd31af8815',
          eksternArbeidsforholdId: 'ARB001-001',
          arbeidsgiverReferanse: '910909088',
          utbetalingsgrad: 50,
          uttakArbeidType: 'ORDINÆRT_ARBEID',
          gradering: true,
          trekkdagerDesimaler: 15.0,
        },
      },
      {
        fom: '2020-01-24',
        tom: '2020-02-13',
        aktiviteter: [
          {
            stønadskontoType: '-',
            prosentArbeid: 100,
            arbeidsforholdId: 'efaf22ef-76aa-4576-8c96-92bd31af8815',
            eksternArbeidsforholdId: 'ARB001-001',
            arbeidsgiverReferanse: '910909088',
            utbetalingsgrad: 0,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 0.0,
          },
        ],
        periodeResultatType: 'INNVILGET',
        begrunnelse: undefined,
        periodeResultatÅrsak: '2011',
        manuellBehandlingÅrsak: '-',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: false,
        periodeType: '-',
        utsettelseType: 'ARBEID',
        oppholdÅrsak: '-',
        mottattDato: '2019-11-01',
        gradertAktivitet: undefined,
      },
      {
        fom: '2020-02-14',
        tom: '2020-02-20',
        aktiviteter: [
          {
            stønadskontoType: 'FELLESPERIODE',
            prosentArbeid: 0,
            arbeidsforholdId: 'efaf22ef-76aa-4576-8c96-92bd31af8815',
            eksternArbeidsforholdId: 'ARB001-001',
            arbeidsgiverReferanse: '910909088',
            utbetalingsgrad: 100,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 5.0,
          },
        ],
        periodeResultatType: 'INNVILGET',
        begrunnelse: undefined,
        periodeResultatÅrsak: '2002',
        manuellBehandlingÅrsak: '-',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: false,
        periodeType: 'FELLESPERIODE',
        utsettelseType: '-',
        oppholdÅrsak: '-',
        mottattDato: '2020-01-24',
        gradertAktivitet: undefined,
      },
    ],
    perioderAnnenpart: [],
    annenForelderHarRett: true,
    aleneomsorg: false,
    årsakFilter: { kreverSammenhengendeUttak: true, kreverSammenhengendeUttakTom: '2021-09-30', utenMinsterett: true, søkerErMor: true },
  },
};

export const AksjonspunktIRevurdering = Template.bind({});
AksjonspunktIRevurdering.args = {
  aksjonspunkter: åpentAksjonspunkt,
  uttaksresultatPerioder: {
    perioderSøker: [
      {
        fom: '2019-10-11',
        tom: '2019-10-31',
        aktiviteter: [
          {
            stønadskontoType: 'FORELDREPENGER_FØR_FØDSEL',
            prosentArbeid: 0,
            arbeidsforholdId: '0716ce9f-d93d-40cd-a52c-c7c569995948',
            eksternArbeidsforholdId: 'ARB001-001',
            arbeidsgiverReferanse: '910909088',
            utbetalingsgrad: 100,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 15.0,
          },
          {
            stønadskontoType: 'MØDREKVOTE',
            prosentArbeid: 51,
            arbeidsforholdId: 'de6cb16e-9520-418c-a438-aa781b0833c2',
            eksternArbeidsforholdId: 'ARB001-002',
            arbeidsgiverReferanse: '994884174',
            utbetalingsgrad: 50,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 15.0,
          },
        ],
        periodeResultatType: 'INNVILGET',
        begrunnelse: undefined,
        periodeResultatÅrsak: '2006',
        manuellBehandlingÅrsak: '-',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: false,
        periodeType: 'FORELDREPENGER_FØR_FØDSEL',
        utsettelseType: '-',
        oppholdÅrsak: '-',
        mottattDato: '2019-09-20',
        gradertAktivitet: undefined,
      },
      {
        fom: '2019-11-01',
        tom: '2019-12-12',
        aktiviteter: [
          {
            stønadskontoType: 'MØDREKVOTE',
            prosentArbeid: 0,
            arbeidsforholdId: '0716ce9f-d93d-40cd-a52c-c7c569995948',
            eksternArbeidsforholdId: 'ARB001-001',
            arbeidsgiverReferanse: '910909088',
            utbetalingsgrad: 100,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 30.0,
          },
        ],
        periodeResultatType: 'INNVILGET',
        begrunnelse: undefined,
        periodeResultatÅrsak: '2003',
        manuellBehandlingÅrsak: '-',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: false,
        periodeType: 'MØDREKVOTE',
        utsettelseType: '-',
        oppholdÅrsak: '-',
        mottattDato: '2019-09-20',
        gradertAktivitet: undefined,
      },
      {
        fom: '2019-12-13',
        tom: '2019-12-26',
        aktiviteter: [
          {
            stønadskontoType: 'MØDREKVOTE',
            prosentArbeid: 100,
            arbeidsforholdId: '0716ce9f-d93d-40cd-a52c-c7c569995948',
            eksternArbeidsforholdId: 'ARB001-001',
            arbeidsgiverReferanse: '910909088',
            utbetalingsgrad: undefined,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 10.0,
          },
        ],
        periodeResultatType: 'MANUELL_BEHANDLING',
        begrunnelse: undefined,
        periodeResultatÅrsak: '4082',
        manuellBehandlingÅrsak: '5010',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: false,
        periodeType: '-',
        utsettelseType: 'ARBEID',
        oppholdÅrsak: '-',
        mottattDato: '2019-12-27',
        gradertAktivitet: undefined,
      },
      {
        fom: '2019-12-27',
        tom: '2020-01-09',
        aktiviteter: [
          {
            stønadskontoType: '-',
            prosentArbeid: 100,
            arbeidsforholdId: '0716ce9f-d93d-40cd-a52c-c7c569995948',
            eksternArbeidsforholdId: 'ARB001-001',
            arbeidsgiverReferanse: '910909088',
            utbetalingsgrad: 0,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 0.0,
          },
        ],
        periodeResultatType: 'INNVILGET',
        begrunnelse: undefined,
        periodeResultatÅrsak: '2011',
        manuellBehandlingÅrsak: '-',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: false,
        periodeType: '-',
        utsettelseType: 'ARBEID',
        oppholdÅrsak: '-',
        mottattDato: '2019-12-27',
        gradertAktivitet: undefined,
      },
    ],
    perioderAnnenpart: [],
    annenForelderHarRett: true,
    aleneomsorg: false,
    årsakFilter: { kreverSammenhengendeUttak: true, kreverSammenhengendeUttakTom: '2021-09-30', utenMinsterett: true, søkerErMor: true },
  },
};

export const ProsessUttakToParter = Template.bind({});
ProsessUttakToParter.args = {
  uttaksresultatPerioder: {
    perioderSøker: [
      {
        fom: '2022-10-20',
        tom: '2022-11-09',
        aktiviteter: [
          {
            stønadskontoType: 'FORELDREPENGER_FØR_FØDSEL',
            prosentArbeid: 0,
            arbeidsforholdId: '7272d1a7-8dbb-4953-bb39-e0742635b2a5',
            eksternArbeidsforholdId: 'ARB001-002',
            arbeidsgiverReferanse: '994884174',
            utbetalingsgrad: 100,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 15.0,
          },
        ],
        periodeResultatType: 'INNVILGET',
        begrunnelse: undefined,
        periodeResultatÅrsak: '2006',
        manuellBehandlingÅrsak: '-',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: false,
        periodeType: 'FORELDREPENGER_FØR_FØDSEL',
        utsettelseType: '-',
        oppholdÅrsak: '-',
        mottattDato: '2022-11-10',
        gradertAktivitet: undefined,
      },
      {
        fom: '2022-11-10',
        tom: '2022-12-21',
        aktiviteter: [
          {
            stønadskontoType: 'MØDREKVOTE',
            prosentArbeid: 0,
            arbeidsforholdId: '7272d1a7-8dbb-4953-bb39-e0742635b2a5',
            eksternArbeidsforholdId: 'ARB001-002',
            arbeidsgiverReferanse: '994884174',
            utbetalingsgrad: 100,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 30.0,
          },
        ],
        periodeResultatType: 'INNVILGET',
        begrunnelse: undefined,
        periodeResultatÅrsak: '2003',
        manuellBehandlingÅrsak: '-',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: false,
        periodeType: 'MØDREKVOTE',
        utsettelseType: '-',
        oppholdÅrsak: '-',
        mottattDato: '2022-11-10',
        gradertAktivitet: undefined,
      },
      {
        fom: '2022-12-22',
        tom: '2022-12-28',
        aktiviteter: [
          {
            stønadskontoType: 'FELLESPERIODE',
            prosentArbeid: 0,
            arbeidsforholdId: '7272d1a7-8dbb-4953-bb39-e0742635b2a5',
            eksternArbeidsforholdId: 'ARB001-002',
            arbeidsgiverReferanse: '994884174',
            utbetalingsgrad: 100,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 5.0,
          },
        ],
        periodeResultatType: 'INNVILGET',
        begrunnelse: undefined,
        periodeResultatÅrsak: '2002',
        manuellBehandlingÅrsak: '-',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: false,
        periodeType: 'FELLESPERIODE',
        utsettelseType: '-',
        oppholdÅrsak: '-',
        mottattDato: '2022-12-01',
        gradertAktivitet: undefined,
      },
      {
        fom: '2022-12-29',
        tom: '2023-01-04',
        aktiviteter: [
          {
            stønadskontoType: 'FELLESPERIODE',
            prosentArbeid: 0,
            arbeidsforholdId: '7272d1a7-8dbb-4953-bb39-e0742635b2a5',
            eksternArbeidsforholdId: 'ARB001-002',
            arbeidsgiverReferanse: '994884174',
            utbetalingsgrad: 100,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 5.0,
          },
        ],
        periodeResultatType: 'INNVILGET',
        begrunnelse: undefined,
        periodeResultatÅrsak: '2002',
        manuellBehandlingÅrsak: '-',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: false,
        periodeType: 'FELLESPERIODE',
        utsettelseType: '-',
        oppholdÅrsak: '-',
        mottattDato: '2022-12-01',
        gradertAktivitet: undefined,
      },
    ],
    perioderAnnenpart: [
      {
        fom: '2022-10-27',
        tom: '2022-11-09',
        aktiviteter: [
          {
            stønadskontoType: 'FEDREKVOTE',
            prosentArbeid: 0,
            arbeidsforholdId: 'b97a7bc5-26ef-4fd8-874e-b475a732c7a8',
            eksternArbeidsforholdId: 'ARB001-003',
            arbeidsgiverReferanse: '910909088',
            utbetalingsgrad: 100,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 10.0,
          },
        ],
        periodeResultatType: 'INNVILGET',
        begrunnelse: undefined,
        periodeResultatÅrsak: '2003',
        manuellBehandlingÅrsak: '-',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: true,
        samtidigUttaksprosent: 100,
        graderingInnvilget: false,
        periodeType: 'FEDREKVOTE',
        utsettelseType: '-',
        oppholdÅrsak: '-',
        mottattDato: '2022-11-17',
        gradertAktivitet: undefined,
      },
      {
        fom: '2022-12-22',
        tom: '2022-12-28',
        aktiviteter: [
          {
            stønadskontoType: 'FEDREKVOTE',
            prosentArbeid: 0,
            arbeidsforholdId: 'b97a7bc5-26ef-4fd8-874e-b475a732c7a8',
            eksternArbeidsforholdId: 'ARB001-003',
            arbeidsgiverReferanse: '910909088',
            utbetalingsgrad: 0,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 0.0,
          },
        ],
        periodeResultatType: 'AVSLÅTT',
        begrunnelse: undefined,
        periodeResultatÅrsak: '4084',
        manuellBehandlingÅrsak: '-',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: false,
        periodeType: 'FEDREKVOTE',
        utsettelseType: '-',
        oppholdÅrsak: '-',
        mottattDato: '2022-11-17',
        gradertAktivitet: undefined,
      },
      {
        fom: '2023-01-05',
        tom: '2023-02-01',
        aktiviteter: [
          {
            stønadskontoType: 'FEDREKVOTE',
            prosentArbeid: 0,
            arbeidsforholdId: 'b97a7bc5-26ef-4fd8-874e-b475a732c7a8',
            eksternArbeidsforholdId: 'ARB001-003',
            arbeidsgiverReferanse: '910909088',
            utbetalingsgrad: 100,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 20.0,
          },
        ],
        periodeResultatType: 'INNVILGET',
        begrunnelse: undefined,
        periodeResultatÅrsak: '2003',
        manuellBehandlingÅrsak: '-',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: false,
        periodeType: 'FEDREKVOTE',
        utsettelseType: '-',
        oppholdÅrsak: '-',
        mottattDato: '2022-11-17',
        gradertAktivitet: undefined,
      },
    ],
    annenForelderHarRett: true,
    aleneomsorg: false,
    årsakFilter: { kreverSammenhengendeUttak: false, kreverSammenhengendeUttakTom: '2021-09-30', utenMinsterett: false, søkerErMor: true },
  },
};

export const AksjonspunktForFar = Template.bind({});
AksjonspunktForFar.args = {
  aksjonspunkter: åpentAksjonspunkt,
  brukerKjønn: NavBrukerKjonn.MANN,
  uttaksresultatPerioder: {
    perioderSøker: [
      {
        fom: '2022-11-10',
        tom: '2022-11-11',
        aktiviteter: [
          {
            stønadskontoType: 'FELLESPERIODE',
            prosentArbeid: 34,
            arbeidsforholdId: 'f41fad23-a318-4ecb-8949-8a8492b65c56',
            eksternArbeidsforholdId: 'ARB001-003',
            arbeidsgiverReferanse: '910909088',
            utbetalingsgrad: undefined,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: true,
            trekkdagerDesimaler: 2.0,
          },
        ],
        periodeResultatType: 'MANUELL_BEHANDLING',
        begrunnelse: undefined,
        periodeResultatÅrsak: '-',
        manuellBehandlingÅrsak: '5010',
        graderingAvslagÅrsak: '4501',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: false,
        periodeType: 'FELLESPERIODE',
        utsettelseType: '-',
        oppholdÅrsak: '-',
        mottattDato: '2023-01-05',
        gradertAktivitet: {
          stønadskontoType: 'FELLESPERIODE',
          prosentArbeid: 34,
          arbeidsforholdId: 'f41fad23-a318-4ecb-8949-8a8492b65c56',
          eksternArbeidsforholdId: 'ARB001-003',
          arbeidsgiverReferanse: '910909088',
          utbetalingsgrad: undefined,
          uttakArbeidType: 'ORDINÆRT_ARBEID',
          gradering: true,
          trekkdagerDesimaler: 2.0,
        },
      },
      {
        fom: '2022-11-12',
        tom: '2022-11-23',
        aktiviteter: [
          {
            stønadskontoType: 'FEDREKVOTE',
            prosentArbeid: 0,
            arbeidsforholdId: 'f41fad23-a318-4ecb-8949-8a8492b65c56',
            eksternArbeidsforholdId: 'ARB001-003',
            arbeidsgiverReferanse: '910909088',
            utbetalingsgrad: 100,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 8.0,
          },
        ],
        periodeResultatType: 'INNVILGET',
        begrunnelse: undefined,
        periodeResultatÅrsak: '2003',
        manuellBehandlingÅrsak: '-',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: true,
        samtidigUttaksprosent: 100,
        graderingInnvilget: false,
        periodeType: 'FEDREKVOTE',
        utsettelseType: '-',
        oppholdÅrsak: '-',
        mottattDato: '2023-01-05',
        gradertAktivitet: undefined,
      },
      {
        fom: '2022-12-22',
        tom: '2023-01-04',
        aktiviteter: [
          {
            stønadskontoType: 'MØDREKVOTE',
            prosentArbeid: 0,
            arbeidsforholdId: 'f41fad23-a318-4ecb-8949-8a8492b65c56',
            eksternArbeidsforholdId: 'ARB001-003',
            arbeidsgiverReferanse: '910909088',
            utbetalingsgrad: 100,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 10.0,
          },
        ],
        periodeResultatType: 'INNVILGET',
        begrunnelse: undefined,
        periodeResultatÅrsak: '2021',
        manuellBehandlingÅrsak: '-',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: false,
        periodeType: 'MØDREKVOTE',
        utsettelseType: '-',
        oppholdÅrsak: '-',
        mottattDato: '2023-01-05',
        gradertAktivitet: undefined,
      },
    ],
    perioderAnnenpart: [
      {
        fom: '2022-10-20',
        tom: '2022-11-09',
        aktiviteter: [
          {
            stønadskontoType: 'FORELDREPENGER_FØR_FØDSEL',
            prosentArbeid: 0,
            arbeidsforholdId: 'a94992b7-e454-458c-800c-a74b4f072c00',
            eksternArbeidsforholdId: 'ARB001-002',
            arbeidsgiverReferanse: '994884174',
            utbetalingsgrad: 100,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 15.0,
          },
        ],
        periodeResultatType: 'INNVILGET',
        begrunnelse: undefined,
        periodeResultatÅrsak: '2006',
        manuellBehandlingÅrsak: '-',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: false,
        periodeType: 'FORELDREPENGER_FØR_FØDSEL',
        utsettelseType: '-',
        oppholdÅrsak: '-',
        mottattDato: '2023-01-05',
        gradertAktivitet: undefined,
      },
      {
        fom: '2022-11-10',
        tom: '2022-12-21',
        aktiviteter: [
          {
            stønadskontoType: '-',
            prosentArbeid: 0,
            arbeidsforholdId: 'a94992b7-e454-458c-800c-a74b4f072c00',
            eksternArbeidsforholdId: 'ARB001-002',
            arbeidsgiverReferanse: '994884174',
            utbetalingsgrad: 0,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 0.0,
          },
        ],
        periodeResultatType: 'INNVILGET',
        begrunnelse: undefined,
        periodeResultatÅrsak: '2027',
        manuellBehandlingÅrsak: '-',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: false,
        periodeType: '-',
        utsettelseType: 'SYKDOM_SKADE',
        oppholdÅrsak: '-',
        mottattDato: '2023-01-05',
        gradertAktivitet: undefined,
      },
    ],
    annenForelderHarRett: true,
    aleneomsorg: false,
    årsakFilter: { kreverSammenhengendeUttak: false, kreverSammenhengendeUttakTom: '2021-09-30', utenMinsterett: false, søkerErMor: false },
  },
};

export const StønadskontoMedUgyldigForbruk = Template.bind({});
StønadskontoMedUgyldigForbruk.args = {
  aksjonspunkter: åpentAksjonspunkt,
  stønadskontoer: {
    ...uttakStonadskontoer,
    stonadskontoer: {
      ...uttakStonadskontoer.stonadskontoer,
      MØDREKVOTE: {
        ...uttakStonadskontoer.stonadskontoer.MØDREKVOTE,
        gyldigForbruk: false,
      },
    },
  },
  uttaksresultatPerioder: {
    perioderSøker: [
      {
        fom: '2022-10-20',
        tom: '2022-11-09',
        aktiviteter: [
          {
            stønadskontoType: 'MØDREKVOTE',
            prosentArbeid: 0,
            arbeidsforholdId: 'de6cb16e-9520-418c-a438-aa781b0833c2',
            eksternArbeidsforholdId: 'ARB001-002',
            arbeidsgiverReferanse: '994884174',
            utbetalingsgrad: undefined,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 15.0,
          },
        ],
        periodeResultatType: 'MANUELL_BEHANDLING',
        begrunnelse: undefined,
        periodeResultatÅrsak: '4002',
        manuellBehandlingÅrsak: '5002',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: false,
        periodeType: 'FORELDREPENGER',
        utsettelseType: '-',
        oppholdÅrsak: '-',
        mottattDato: '2023-01-05',
        gradertAktivitet: undefined,
      },
    ],
    perioderAnnenpart: [],
    annenForelderHarRett: true,
    aleneomsorg: false,
    årsakFilter: { kreverSammenhengendeUttak: false, kreverSammenhengendeUttakTom: '2021-09-30', utenMinsterett: false, søkerErMor: true },
  },
};

export const VisAdvarselNårProsentIArbeidTotaltErMindreEnn100Prosent = Template.bind({});
VisAdvarselNårProsentIArbeidTotaltErMindreEnn100Prosent.args = {
  aksjonspunkter: åpentAksjonspunkt,
  uttaksresultatPerioder: {
    perioderSøker: [
      {
        fom: '2022-10-20',
        tom: '2022-11-09',
        aktiviteter: [
          {
            stønadskontoType: 'MØDREKVOTE',
            prosentArbeid: 0,
            arbeidsforholdId: 'de6cb16e-9520-418c-a438-aa781b0833c2',
            eksternArbeidsforholdId: 'ARB001-002',
            arbeidsgiverReferanse: '994884174',
            utbetalingsgrad: undefined,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 15.0,
          },
        ],
        periodeResultatType: 'MANUELL_BEHANDLING',
        begrunnelse: undefined,
        periodeResultatÅrsak: '4002',
        manuellBehandlingÅrsak: '5002',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: false,
        periodeType: 'FORELDREPENGER',
        utsettelseType: utsettelseArsakCodes.ARBEID,
        oppholdÅrsak: '-',
        mottattDato: '2023-01-05',
        gradertAktivitet: undefined,
      },
    ],
    perioderAnnenpart: [],
    annenForelderHarRett: true,
    aleneomsorg: false,
    årsakFilter: { kreverSammenhengendeUttak: false, kreverSammenhengendeUttakTom: '2021-09-30', utenMinsterett: false, søkerErMor: true },
  },
};

export const VisAdvarselNårUtbetalingsgradOgProsentArbeidOverstiger100Prosent = Template.bind({});
VisAdvarselNårUtbetalingsgradOgProsentArbeidOverstiger100Prosent.args = {
  aksjonspunkter: åpentAksjonspunkt,
  uttaksresultatPerioder: {
    perioderSøker: [
      {
        fom: '2022-10-20',
        tom: '2022-11-09',
        aktiviteter: [
          {
            stønadskontoType: 'MØDREKVOTE',
            prosentArbeid: 51,
            arbeidsforholdId: 'de6cb16e-9520-418c-a438-aa781b0833c2',
            eksternArbeidsforholdId: 'ARB001-002',
            arbeidsgiverReferanse: '994884174',
            utbetalingsgrad: 50,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 15.0,
          },
        ],
        periodeResultatType: 'MANUELL_BEHANDLING',
        begrunnelse: undefined,
        periodeResultatÅrsak: '4002',
        manuellBehandlingÅrsak: '5002',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: false,
        periodeType: 'FORELDREPENGER',
        utsettelseType: utsettelseArsakCodes.ARBEID,
        oppholdÅrsak: '-',
        mottattDato: '2023-01-05',
        gradertAktivitet: undefined,
      },
    ],
    perioderAnnenpart: [],
    annenForelderHarRett: true,
    aleneomsorg: false,
    årsakFilter: { kreverSammenhengendeUttak: false, kreverSammenhengendeUttakTom: '2021-09-30', utenMinsterett: false, søkerErMor: true },
  },
};

export const VisOppholdsperiode = Template.bind({});
VisOppholdsperiode.args = {
  aksjonspunkter: åpentAksjonspunkt,
  uttaksresultatPerioder: {
    perioderSøker: [
      {
        fom: '2023-02-15',
        tom: '2023-05-05',
        aktiviteter: [],
        periodeResultatType: 'INNVILGET',
        begrunnelse: undefined,
        periodeResultatÅrsak: '-',
        manuellBehandlingÅrsak: '-',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: false,
        periodeType: '-',
        utsettelseType: '-',
        oppholdÅrsak: 'UTTAK_FEDREKVOTE_ANNEN_FORELDER',
        mottattDato: '2023-01-18',
        gradertAktivitet: undefined,
      },
    ],
    perioderAnnenpart: [
      {
        fom: '2023-02-03',
        tom: '2023-02-14',
        aktiviteter: [
          {
            stønadskontoType: 'FEDREKVOTE',
            prosentArbeid: 0,
            arbeidsforholdId: undefined,
            eksternArbeidsforholdId: undefined,
            arbeidsgiverReferanse: '886998562',
            utbetalingsgrad: 100,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 8.0,
          },
          {
            stønadskontoType: 'FEDREKVOTE',
            prosentArbeid: 0,
            arbeidsforholdId: undefined,
            eksternArbeidsforholdId: undefined,
            arbeidsgiverReferanse: '987195428',
            utbetalingsgrad: 100,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 8.0,
          },
          {
            stønadskontoType: 'FEDREKVOTE',
            prosentArbeid: 0,
            arbeidsforholdId: undefined,
            eksternArbeidsforholdId: undefined,
            arbeidsgiverReferanse: '972315575',
            utbetalingsgrad: 100,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 8.0,
          },
        ],
        periodeResultatType: 'INNVILGET',
        begrunnelse: undefined,
        periodeResultatÅrsak: '2003',
        manuellBehandlingÅrsak: '-',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: false,
        periodeType: 'FEDREKVOTE',
        utsettelseType: '-',
        oppholdÅrsak: '-',
        mottattDato: '2022-11-28',
        gradertAktivitet: undefined,
      },
      {
        fom: '2023-05-16',
        tom: '2023-05-17',
        aktiviteter: [
          {
            stønadskontoType: 'FEDREKVOTE',
            prosentArbeid: 0,
            arbeidsforholdId: undefined,
            eksternArbeidsforholdId: undefined,
            arbeidsgiverReferanse: '987195428',
            utbetalingsgrad: 0,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 0.0,
          },
          {
            stønadskontoType: 'FEDREKVOTE',
            prosentArbeid: 0,
            arbeidsforholdId: undefined,
            eksternArbeidsforholdId: undefined,
            arbeidsgiverReferanse: '886998562',
            utbetalingsgrad: 0,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 0.0,
          },
          {
            stønadskontoType: 'FEDREKVOTE',
            prosentArbeid: 0,
            arbeidsforholdId: undefined,
            eksternArbeidsforholdId: undefined,
            arbeidsgiverReferanse: '972315575',
            utbetalingsgrad: 0,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: false,
            trekkdagerDesimaler: 0.0,
          },
        ],
        periodeResultatType: 'AVSLÅTT',
        begrunnelse: undefined,
        periodeResultatÅrsak: '4084',
        manuellBehandlingÅrsak: '-',
        graderingAvslagÅrsak: '-',
        flerbarnsdager: false,
        samtidigUttak: false,
        samtidigUttaksprosent: undefined,
        graderingInnvilget: false,
        periodeType: 'FEDREKVOTE',
        utsettelseType: '-',
        oppholdÅrsak: '-',
        mottattDato: '2022-11-28',
        gradertAktivitet: undefined,
      },
    ],
    annenForelderHarRett: true,
    aleneomsorg: false,
    årsakFilter: { kreverSammenhengendeUttak: true, kreverSammenhengendeUttakTom: '2021-09-30', utenMinsterett: true, søkerErMor: true },
  },
};
