enum SupportTabs {
  TIL_BESLUTTER = 'TIL_BESLUTTER',
  FRA_BESLUTTER = 'FRA_BESLUTTER',
  HISTORIKK = 'HISTORIKK',
  HISTORIKK_V2 = 'HISTORIKK_V2',
  MELDINGER = 'MELDINGER',
  DOKUMENTER = 'DOKUMENTER',
  NOTATER = 'NOTATER',
}

export default SupportTabs;
