import { type ComponentProps } from 'react';

import type { Meta, StoryObj } from '@storybook/react';
import { action } from 'storybook/actions';

import { AksjonspunktKode } from '@navikt/fp-kodeverk';
import { type PanelDataArgs, withMellomlagretFormData, withPanelData } from '@navikt/fp-storybook-utils';
import type {
  Aksjonspunkt,
  ArbeidsgiverOpplysningerPerId,
  BehandlingFpSak,
  Fagsak,
  FamilieHendelse,
  Personoversikt,
  Soknad,
  StønadskontoType,
  UttakStonadskontoer,
} from '@navikt/fp-types';

import { UttakProsessIndex } from './UttakProsessIndex';

const åpentAksjonspunkt: Aksjonspunkt[] = [
  {
    definisjon: AksjonspunktKode.FASTSETT_UTTAKPERIODER,
    status: 'OPPR',
    kanLoses: true,
    toTrinnsBehandling: true,
    aksjonspunktType: 'MANU',
    vilkarType: 'FP_VK_5',
    erAktivt: true,
  },
];

const familiehendelse = {
  fødselTermin: {
    fødselsdato: '2019-11-04',
  },
} as FamilieHendelse;

const behandling = {
  uuid: '1',
  versjon: 1,
  type: 'BT-002',
  behandlingsresultat: {
    skjæringstidspunkt: {
      dato: '2019-10-14',
    },
  },
  status: 'UTRED',
  språkkode: '-',
} as BehandlingFpSak;

const uttakStonadskontoer = {
  tapteDagerFpff: 1,
  stonadskontoer: {
    FEDREKVOTE: {
      stonadskontotype: 'FEDREKVOTE',
      maxDager: 75,
      saldo: 50,
      aktivitetSaldoDtoList: [
        {
          aktivitetIdentifikator: {
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            arbeidsgiverReferanse: '910909088',
          },
          saldo: 50,
        },
      ],
      gyldigForbruk: true,
    },
    MØDREKVOTE: {
      stonadskontotype: 'MØDREKVOTE',
      maxDager: 75,
      saldo: 35,
      aktivitetSaldoDtoList: [
        {
          aktivitetIdentifikator: {
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            arbeidsgiverReferanse: '910909088',
          },
          saldo: 35,
        },
      ],
      gyldigForbruk: true,
    },
    FELLESPERIODE: {
      stonadskontotype: 'FELLESPERIODE',
      maxDager: 80,
      saldo: 80,
      aktivitetSaldoDtoList: [
        {
          aktivitetIdentifikator: {
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            arbeidsgiverReferanse: '910909088',
          },
          saldo: 80,
        },
      ],
      gyldigForbruk: true,
    },
    FORELDREPENGER_FØR_FØDSEL: {
      stonadskontotype: 'FORELDREPENGER_FØR_FØDSEL',
      maxDager: 15,
      saldo: 0,
      aktivitetSaldoDtoList: [
        {
          aktivitetIdentifikator: {
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            arbeidsgiverReferanse: '910909088',
          },
          saldo: 0,
        },
      ],
      gyldigForbruk: true,
    },
  },
} satisfies UttakStonadskontoer;

const soknad = {
  soknadType: 'ST-001',
  mottattDato: '2019-11-18',
  søknadsfrist: {
    mottattDato: '2019-11-18',
    utledetSøknadsfrist: '2020-01-31',
    søknadsperiodeStart: '2019-10-14',
    søknadsperiodeSlutt: '2020-02-02',
    dagerOversittetFrist: -74,
  },
} as Soknad;

const arbeidsgiverOpplysningerPerId: ArbeidsgiverOpplysningerPerId = {
  342352362: {
    erPrivatPerson: false,
    referanse: '342352362',
    identifikator: '342352362',
    navn: 'Lagt til av saksbehandler',
  },
  910909088: {
    erPrivatPerson: false,
    referanse: '910909088',
    identifikator: '910909088',
    navn: 'BEDRIFT AS',
  },
  994884174: {
    erPrivatPerson: false,
    referanse: '994884174',
    identifikator: '994884174',
    navn: 'Nav',
  },
};

const meta = {
  title: 'prosess/prosess-uttak',
  component: UttakProsessIndex,
  decorators: [withMellomlagretFormData, withPanelData],
  args: {
    behandling,
    uttakStonadskontoer,
    soknad,
    personoversikt: {
      bruker: {
        kjønn: 'K',
      },
    } as Personoversikt,
    kanOverstyre: false,
    familiehendelse,
    oppdaterStønadskontoer: v => {
      action('button-click')(v);
      return Promise.resolve<UttakStonadskontoer>(uttakStonadskontoer);
    },
    arbeidsgiverOpplysningerPerId,
    annenForelderUttakEøs: undefined,
  },
  render: args => <UttakProsessIndex {...args} />,
} satisfies Meta<PanelDataArgs & ComponentProps<typeof UttakProsessIndex>>;
export default meta;

type Story = StoryObj<typeof meta>;

export const AksjonspunktDerValgtStønadskontoIkkeFinnes: Story = {
  args: {
    aksjonspunkterForPanel: åpentAksjonspunkt,
    uttaksresultat: {
      perioderSøker: [
        {
          fom: '2022-10-20',
          tom: '2022-11-09',
          aktiviteter: [
            {
              stønadskontoType: 'FORELDREPENGER' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: 'de6cb16e-9520-418c-a438-aa781b0833c2',
              eksternArbeidsforholdId: 'ARB001-002',
              arbeidsgiverReferanse: '994884174',
              utbetalingsgrad: undefined,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 15.0,
            },
            {
              stønadskontoType: 'FORELDREPENGER' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: 'de6cb16e-9520-418c-a438-aa781b0833c1',
              eksternArbeidsforholdId: 'ARB001-001',
              arbeidsgiverReferanse: '910909088',
              utbetalingsgrad: undefined,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 14.0,
            },
          ],
          periodeResultatType: 'MANUELL_BEHANDLING',
          begrunnelse: undefined,
          periodeResultatÅrsak: '4072',
          manuellBehandlingÅrsak: '5002',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: 'FORELDREPENGER',
          utsettelseType: '-',
          oppholdÅrsak: '-',
          mottattDato: '2023-01-05',
          gradertAktivitet: undefined,
        },
        {
          fom: '2022-11-10',
          tom: '2022-12-21',
          aktiviteter: [
            {
              stønadskontoType: 'MØDREKVOTE' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: 'de6cb16e-9520-418c-a438-aa781b0833c2',
              eksternArbeidsforholdId: 'ARB001-002',
              arbeidsgiverReferanse: '994884174',
              utbetalingsgrad: 0,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 30.0,
            },
          ],
          periodeResultatType: 'AVSLÅTT',
          begrunnelse: undefined,
          periodeResultatÅrsak: '4103',
          manuellBehandlingÅrsak: '-',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: 'FORELDREPENGER',
          utsettelseType: '-',
          oppholdÅrsak: '-',
          mottattDato: undefined,
          gradertAktivitet: undefined,
        },
      ],
      perioderAnnenpart: [],
      årsakFilter: { kreverSammenhengendeUttakTom: '2021-09-30', utenMinsterett: false, søkerErMor: true },
      endringsdato: '2022-10-20',
    },
  },
};

export const PeriodeMedGraderingUtenAksjonspunkt: Story = {
  args: {
    kanOverstyre: true,
    uttaksresultat: {
      perioderSøker: [
        {
          fom: '2019-10-11',
          tom: '2019-10-31',
          aktiviteter: [
            {
              stønadskontoType: 'FORELDREPENGER_FØR_FØDSEL' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: 'efaf22ef-76aa-4576-8c96-92bd31af8815',
              eksternArbeidsforholdId: 'ARB001-001',
              arbeidsgiverReferanse: '910909088',
              utbetalingsgrad: 100,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 15.0,
            },
          ],
          periodeResultatType: 'INNVILGET',
          begrunnelse: undefined,
          periodeResultatÅrsak: '2006',
          manuellBehandlingÅrsak: '-',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: 'FORELDREPENGER_FØR_FØDSEL',
          utsettelseType: '-',
          oppholdÅrsak: '-',
          mottattDato: '2019-11-01',
          gradertAktivitet: undefined,
        },
        {
          fom: '2019-11-01',
          tom: '2019-12-12',
          aktiviteter: [
            {
              stønadskontoType: 'MØDREKVOTE' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: 'efaf22ef-76aa-4576-8c96-92bd31af8815',
              eksternArbeidsforholdId: 'ARB001-001',
              arbeidsgiverReferanse: '910909088',
              utbetalingsgrad: 100,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 30.0,
            },
          ],
          periodeResultatType: 'INNVILGET',
          begrunnelse: undefined,
          periodeResultatÅrsak: '2003',
          manuellBehandlingÅrsak: '-',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: 'MØDREKVOTE',
          utsettelseType: '-',
          oppholdÅrsak: '-',
          mottattDato: '2019-11-01',
          gradertAktivitet: undefined,
        },
        {
          fom: '2019-12-13',
          tom: '2020-01-23',
          aktiviteter: [
            {
              stønadskontoType: 'MØDREKVOTE' satisfies StønadskontoType,
              prosentArbeid: 50,
              arbeidsforholdId: 'efaf22ef-76aa-4576-8c96-92bd31af8815',
              eksternArbeidsforholdId: 'ARB001-001',
              arbeidsgiverReferanse: '910909088',
              utbetalingsgrad: 50,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: true,
              trekkdagerDesimaler: 15.0,
            },
          ],
          periodeResultatType: 'INNVILGET',
          begrunnelse: undefined,
          periodeResultatÅrsak: '2031',
          manuellBehandlingÅrsak: '-',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: true,
          periodeType: 'MØDREKVOTE',
          utsettelseType: '-',
          oppholdÅrsak: '-',
          mottattDato: '2019-11-01',
          gradertAktivitet: {
            stønadskontoType: 'MØDREKVOTE' satisfies StønadskontoType,
            prosentArbeid: 50,
            arbeidsforholdId: 'efaf22ef-76aa-4576-8c96-92bd31af8815',
            eksternArbeidsforholdId: 'ARB001-001',
            arbeidsgiverReferanse: '910909088',
            utbetalingsgrad: 50,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: true,
            trekkdagerDesimaler: 15.0,
          },
        },
        {
          fom: '2020-01-24',
          tom: '2020-02-13',
          aktiviteter: [
            {
              prosentArbeid: 100,
              arbeidsforholdId: 'efaf22ef-76aa-4576-8c96-92bd31af8815',
              eksternArbeidsforholdId: 'ARB001-001',
              arbeidsgiverReferanse: '910909088',
              utbetalingsgrad: 0,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 0.0,
            },
          ],
          periodeResultatType: 'INNVILGET',
          begrunnelse: undefined,
          periodeResultatÅrsak: '2011',
          manuellBehandlingÅrsak: '-',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: '-',
          utsettelseType: 'ARBEID',
          oppholdÅrsak: '-',
          mottattDato: '2019-11-01',
          gradertAktivitet: undefined,
        },
        {
          fom: '2020-02-14',
          tom: '2020-02-20',
          aktiviteter: [
            {
              stønadskontoType: 'FELLESPERIODE' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: 'efaf22ef-76aa-4576-8c96-92bd31af8815',
              eksternArbeidsforholdId: 'ARB001-001',
              arbeidsgiverReferanse: '910909088',
              utbetalingsgrad: 100,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 5.0,
            },
          ],
          periodeResultatType: 'INNVILGET',
          begrunnelse: undefined,
          periodeResultatÅrsak: '2002',
          manuellBehandlingÅrsak: '-',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: 'FELLESPERIODE',
          utsettelseType: '-',
          oppholdÅrsak: '-',
          mottattDato: '2020-01-24',
          gradertAktivitet: undefined,
        },
      ],
      perioderAnnenpart: [],
      årsakFilter: { kreverSammenhengendeUttakTom: '2021-09-30', utenMinsterett: true, søkerErMor: true },
      endringsdato: '2019-10-11',
    },
  },
};

export const AksjonspunktIRevurdering: Story = {
  args: {
    aksjonspunkterForPanel: åpentAksjonspunkt,
    uttaksresultat: {
      perioderSøker: [
        {
          fom: '2019-10-11',
          tom: '2019-10-31',
          aktiviteter: [
            {
              stønadskontoType: 'FORELDREPENGER_FØR_FØDSEL' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: '0716ce9f-d93d-40cd-a52c-c7c569995948',
              eksternArbeidsforholdId: 'ARB001-001',
              arbeidsgiverReferanse: '910909088',
              utbetalingsgrad: 100,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 15.0,
            },
            {
              stønadskontoType: 'MØDREKVOTE' satisfies StønadskontoType,
              prosentArbeid: 51,
              arbeidsforholdId: 'de6cb16e-9520-418c-a438-aa781b0833c2',
              eksternArbeidsforholdId: 'ARB001-002',
              arbeidsgiverReferanse: '994884174',
              utbetalingsgrad: 50,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 15.0,
            },
          ],
          periodeResultatType: 'INNVILGET',
          begrunnelse: undefined,
          periodeResultatÅrsak: '2006',
          manuellBehandlingÅrsak: '-',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: 'FORELDREPENGER_FØR_FØDSEL',
          utsettelseType: '-',
          oppholdÅrsak: '-',
          mottattDato: '2019-09-20',
          gradertAktivitet: undefined,
        },
        {
          fom: '2019-11-01',
          tom: '2019-12-12',
          aktiviteter: [
            {
              stønadskontoType: 'MØDREKVOTE' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: '0716ce9f-d93d-40cd-a52c-c7c569995948',
              eksternArbeidsforholdId: 'ARB001-001',
              arbeidsgiverReferanse: '910909088',
              utbetalingsgrad: 100,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 30.0,
            },
          ],
          periodeResultatType: 'INNVILGET',
          begrunnelse: undefined,
          periodeResultatÅrsak: '2003',
          manuellBehandlingÅrsak: '-',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: 'MØDREKVOTE',
          utsettelseType: '-',
          oppholdÅrsak: '-',
          mottattDato: '2019-09-20',
          gradertAktivitet: undefined,
        },
        {
          fom: '2019-12-13',
          tom: '2019-12-26',
          aktiviteter: [
            {
              stønadskontoType: 'MØDREKVOTE' satisfies StønadskontoType,
              prosentArbeid: 100,
              arbeidsforholdId: '0716ce9f-d93d-40cd-a52c-c7c569995948',
              eksternArbeidsforholdId: 'ARB001-001',
              arbeidsgiverReferanse: '910909088',
              utbetalingsgrad: undefined,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 10.0,
            },
          ],
          periodeResultatType: 'MANUELL_BEHANDLING',
          begrunnelse: undefined,
          periodeResultatÅrsak: '4082',
          manuellBehandlingÅrsak: '5010',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: '-',
          utsettelseType: 'ARBEID',
          oppholdÅrsak: '-',
          mottattDato: '2019-12-27',
          gradertAktivitet: undefined,
        },
        {
          fom: '2019-12-27',
          tom: '2020-01-09',
          aktiviteter: [
            {
              prosentArbeid: 100,
              arbeidsforholdId: '0716ce9f-d93d-40cd-a52c-c7c569995948',
              eksternArbeidsforholdId: 'ARB001-001',
              arbeidsgiverReferanse: '910909088',
              utbetalingsgrad: 0,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 0.0,
            },
          ],
          periodeResultatType: 'INNVILGET',
          begrunnelse: undefined,
          periodeResultatÅrsak: '2011',
          manuellBehandlingÅrsak: '-',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: '-',
          utsettelseType: 'ARBEID',
          oppholdÅrsak: '-',
          mottattDato: '2019-12-27',
          gradertAktivitet: undefined,
        },
      ],
      perioderAnnenpart: [],
      årsakFilter: { kreverSammenhengendeUttakTom: '2021-09-30', utenMinsterett: true, søkerErMor: true },
      endringsdato: '2019-10-11',
    },
  },
};

export const ProsessUttakToParter: Story = {
  args: {
    uttaksresultat: {
      perioderSøker: [
        {
          fom: '2022-10-20',
          tom: '2022-11-09',
          aktiviteter: [
            {
              stønadskontoType: 'FORELDREPENGER_FØR_FØDSEL' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: '7272d1a7-8dbb-4953-bb39-e0742635b2a5',
              eksternArbeidsforholdId: 'ARB001-002',
              arbeidsgiverReferanse: '994884174',
              utbetalingsgrad: 100,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 15.0,
            },
          ],
          periodeResultatType: 'INNVILGET',
          begrunnelse: undefined,
          periodeResultatÅrsak: '2006',
          manuellBehandlingÅrsak: '-',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: 'FORELDREPENGER_FØR_FØDSEL',
          utsettelseType: '-',
          oppholdÅrsak: '-',
          mottattDato: '2022-11-10',
          gradertAktivitet: undefined,
        },
        {
          fom: '2022-11-10',
          tom: '2022-12-21',
          aktiviteter: [
            {
              stønadskontoType: 'MØDREKVOTE' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: '7272d1a7-8dbb-4953-bb39-e0742635b2a5',
              eksternArbeidsforholdId: 'ARB001-002',
              arbeidsgiverReferanse: '994884174',
              utbetalingsgrad: 100,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 30.0,
            },
          ],
          periodeResultatType: 'INNVILGET',
          begrunnelse: undefined,
          periodeResultatÅrsak: '2003',
          manuellBehandlingÅrsak: '-',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: 'MØDREKVOTE',
          utsettelseType: '-',
          oppholdÅrsak: '-',
          mottattDato: '2022-11-10',
          gradertAktivitet: undefined,
        },
        {
          fom: '2022-12-22',
          tom: '2022-12-28',
          aktiviteter: [
            {
              stønadskontoType: 'FELLESPERIODE' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: '7272d1a7-8dbb-4953-bb39-e0742635b2a5',
              eksternArbeidsforholdId: 'ARB001-002',
              arbeidsgiverReferanse: '994884174',
              utbetalingsgrad: 100,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 5.0,
            },
          ],
          periodeResultatType: 'INNVILGET',
          begrunnelse: undefined,
          periodeResultatÅrsak: '2002',
          manuellBehandlingÅrsak: '-',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: 'FELLESPERIODE',
          utsettelseType: '-',
          oppholdÅrsak: '-',
          mottattDato: '2022-12-01',
          gradertAktivitet: undefined,
        },
        {
          fom: '2022-12-29',
          tom: '2023-01-04',
          aktiviteter: [
            {
              stønadskontoType: 'FELLESPERIODE' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: '7272d1a7-8dbb-4953-bb39-e0742635b2a5',
              eksternArbeidsforholdId: 'ARB001-002',
              arbeidsgiverReferanse: '994884174',
              utbetalingsgrad: 100,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 5.0,
            },
          ],
          periodeResultatType: 'INNVILGET',
          begrunnelse: undefined,
          periodeResultatÅrsak: '4072',
          manuellBehandlingÅrsak: '-',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: 'FELLESPERIODE',
          utsettelseType: '-',
          oppholdÅrsak: '-',
          mottattDato: '2022-12-01',
          gradertAktivitet: undefined,
        },
      ],
      perioderAnnenpart: [
        {
          fom: '2022-10-27',
          tom: '2022-11-09',
          aktiviteter: [
            {
              stønadskontoType: 'FEDREKVOTE' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: 'b97a7bc5-26ef-4fd8-874e-b475a732c7a8',
              eksternArbeidsforholdId: 'ARB001-003',
              arbeidsgiverReferanse: '910909088',
              utbetalingsgrad: 100,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 10.0,
            },
          ],
          periodeResultatType: 'INNVILGET',
          begrunnelse: undefined,
          periodeResultatÅrsak: '2003',
          manuellBehandlingÅrsak: '-',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: true,
          samtidigUttaksprosent: 100,
          graderingInnvilget: false,
          periodeType: 'FEDREKVOTE',
          utsettelseType: '-',
          oppholdÅrsak: '-',
          mottattDato: '2022-11-17',
          gradertAktivitet: undefined,
        },
        {
          fom: '2022-12-22',
          tom: '2022-12-28',
          aktiviteter: [
            {
              stønadskontoType: 'FEDREKVOTE' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: 'b97a7bc5-26ef-4fd8-874e-b475a732c7a8',
              eksternArbeidsforholdId: 'ARB001-003',
              arbeidsgiverReferanse: '910909088',
              utbetalingsgrad: 0,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 0.0,
            },
          ],
          periodeResultatType: 'AVSLÅTT',
          begrunnelse: undefined,
          periodeResultatÅrsak: '4084',
          manuellBehandlingÅrsak: '-',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: 'FEDREKVOTE',
          utsettelseType: '-',
          oppholdÅrsak: '-',
          mottattDato: '2022-11-17',
          gradertAktivitet: undefined,
        },
        {
          fom: '2023-01-05',
          tom: '2023-02-01',
          aktiviteter: [
            {
              stønadskontoType: 'FEDREKVOTE' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: 'b97a7bc5-26ef-4fd8-874e-b475a732c7a8',
              eksternArbeidsforholdId: 'ARB001-003',
              arbeidsgiverReferanse: '910909088',
              utbetalingsgrad: 100,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 20.0,
            },
          ],
          periodeResultatType: 'INNVILGET',
          begrunnelse: undefined,
          periodeResultatÅrsak: '2003',
          manuellBehandlingÅrsak: '-',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: 'FEDREKVOTE',
          utsettelseType: '-',
          oppholdÅrsak: '-',
          mottattDato: '2022-11-17',
          gradertAktivitet: undefined,
        },
      ],
      årsakFilter: { kreverSammenhengendeUttakTom: '2021-09-30', utenMinsterett: false, søkerErMor: true },
      endringsdato: '2022-10-20',
    },
  },
};

export const AksjonspunktForFar: Story = {
  args: {
    aksjonspunkterForPanel: åpentAksjonspunkt,
    personoversikt: {
      bruker: {
        kjønn: 'M',
      },
    } as Personoversikt,
    uttaksresultat: {
      perioderSøker: [
        {
          fom: '2022-11-10',
          tom: '2022-11-11',
          aktiviteter: [
            {
              stønadskontoType: 'FELLESPERIODE' satisfies StønadskontoType,
              prosentArbeid: 34,
              arbeidsforholdId: 'f41fad23-a318-4ecb-8949-8a8492b65c56',
              eksternArbeidsforholdId: 'ARB001-003',
              arbeidsgiverReferanse: '910909088',
              utbetalingsgrad: undefined,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: true,
              trekkdagerDesimaler: 2.0,
            },
          ],
          periodeResultatType: 'MANUELL_BEHANDLING',
          begrunnelse: undefined,
          periodeResultatÅrsak: '-',
          manuellBehandlingÅrsak: '5010',
          graderingAvslagÅrsak: '4501',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: 'FELLESPERIODE',
          utsettelseType: '-',
          oppholdÅrsak: '-',
          mottattDato: '2023-01-05',
          gradertAktivitet: {
            stønadskontoType: 'FELLESPERIODE' satisfies StønadskontoType,
            prosentArbeid: 34,
            arbeidsforholdId: 'f41fad23-a318-4ecb-8949-8a8492b65c56',
            eksternArbeidsforholdId: 'ARB001-003',
            arbeidsgiverReferanse: '910909088',
            utbetalingsgrad: undefined,
            uttakArbeidType: 'ORDINÆRT_ARBEID',
            gradering: true,
            trekkdagerDesimaler: 2.0,
          },
        },
        {
          fom: '2022-11-12',
          tom: '2022-11-23',
          aktiviteter: [
            {
              stønadskontoType: 'FEDREKVOTE' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: 'f41fad23-a318-4ecb-8949-8a8492b65c56',
              eksternArbeidsforholdId: 'ARB001-003',
              arbeidsgiverReferanse: '910909088',
              utbetalingsgrad: 100,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 8.0,
            },
          ],
          periodeResultatType: 'INNVILGET',
          begrunnelse: undefined,
          periodeResultatÅrsak: '2003',
          manuellBehandlingÅrsak: '-',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: true,
          samtidigUttaksprosent: 100,
          graderingInnvilget: false,
          periodeType: 'FEDREKVOTE',
          utsettelseType: '-',
          oppholdÅrsak: '-',
          mottattDato: '2023-01-05',
          gradertAktivitet: undefined,
        },
        {
          fom: '2022-12-22',
          tom: '2023-01-04',
          aktiviteter: [
            {
              stønadskontoType: 'MØDREKVOTE' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: 'f41fad23-a318-4ecb-8949-8a8492b65c56',
              eksternArbeidsforholdId: 'ARB001-003',
              arbeidsgiverReferanse: '910909088',
              utbetalingsgrad: 100,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 10.0,
            },
          ],
          periodeResultatType: 'INNVILGET',
          begrunnelse: undefined,
          periodeResultatÅrsak: '2021',
          manuellBehandlingÅrsak: '-',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: 'MØDREKVOTE',
          utsettelseType: '-',
          oppholdÅrsak: '-',
          mottattDato: '2023-01-05',
          gradertAktivitet: undefined,
        },
      ],
      perioderAnnenpart: [
        {
          fom: '2022-10-20',
          tom: '2022-11-09',
          aktiviteter: [
            {
              stønadskontoType: 'FORELDREPENGER_FØR_FØDSEL' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: 'a94992b7-e454-458c-800c-a74b4f072c00',
              eksternArbeidsforholdId: 'ARB001-002',
              arbeidsgiverReferanse: '994884174',
              utbetalingsgrad: 100,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 15.0,
            },
          ],
          periodeResultatType: 'INNVILGET',
          begrunnelse: undefined,
          periodeResultatÅrsak: '2006',
          manuellBehandlingÅrsak: '-',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: 'FORELDREPENGER_FØR_FØDSEL',
          utsettelseType: '-',
          oppholdÅrsak: '-',
          mottattDato: '2023-01-05',
          gradertAktivitet: undefined,
        },
        {
          fom: '2022-11-10',
          tom: '2022-12-21',
          aktiviteter: [
            {
              prosentArbeid: 0,
              arbeidsforholdId: 'a94992b7-e454-458c-800c-a74b4f072c00',
              eksternArbeidsforholdId: 'ARB001-002',
              arbeidsgiverReferanse: '994884174',
              utbetalingsgrad: 0,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 0.0,
            },
          ],
          periodeResultatType: 'INNVILGET',
          begrunnelse: undefined,
          periodeResultatÅrsak: '2027',
          manuellBehandlingÅrsak: '-',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: '-',
          utsettelseType: 'SYKDOM_SKADE',
          oppholdÅrsak: '-',
          mottattDato: '2023-01-05',
          gradertAktivitet: undefined,
        },
      ],
      årsakFilter: { kreverSammenhengendeUttakTom: '2021-09-30', utenMinsterett: false, søkerErMor: false },
      endringsdato: '2022-11-10',
    },
  },
};

const uttakStønadskontoerForUgyldigForbrukt = {
  ...uttakStonadskontoer,
  stonadskontoer: {
    ...uttakStonadskontoer.stonadskontoer,
    MØDREKVOTE: {
      ...uttakStonadskontoer.stonadskontoer.MØDREKVOTE,
      gyldigForbruk: false,
    },
  },
} satisfies UttakStonadskontoer;

export const StønadskontoMedUgyldigForbruk: Story = {
  args: {
    aksjonspunkterForPanel: åpentAksjonspunkt,
    uttakStonadskontoer: uttakStønadskontoerForUgyldigForbrukt,
    oppdaterStønadskontoer: v => {
      action('button-click')(v);
      return Promise.resolve(uttakStønadskontoerForUgyldigForbrukt);
    },
    uttaksresultat: {
      perioderSøker: [
        {
          fom: '2022-10-20',
          tom: '2022-11-09',
          aktiviteter: [
            {
              stønadskontoType: 'MØDREKVOTE' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: 'de6cb16e-9520-418c-a438-aa781b0833c2',
              eksternArbeidsforholdId: 'ARB001-002',
              arbeidsgiverReferanse: '994884174',
              utbetalingsgrad: undefined,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 15.0,
            },
          ],
          periodeResultatType: 'MANUELL_BEHANDLING',
          begrunnelse: undefined,
          periodeResultatÅrsak: '4072',
          manuellBehandlingÅrsak: '5002',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: 'FORELDREPENGER',
          utsettelseType: '-',
          oppholdÅrsak: '-',
          mottattDato: '2023-01-05',
          gradertAktivitet: undefined,
        },
      ],
      perioderAnnenpart: [],
      årsakFilter: { kreverSammenhengendeUttakTom: '2021-09-30', utenMinsterett: false, søkerErMor: true },
      endringsdato: '2022-10-20',
    },
  },
};

export const VisAdvarselNårProsentIArbeidTotaltErMindreEnn100Prosent: Story = {
  args: {
    aksjonspunkterForPanel: åpentAksjonspunkt,
    uttaksresultat: {
      perioderSøker: [
        {
          fom: '2022-10-20',
          tom: '2022-11-09',
          aktiviteter: [
            {
              stønadskontoType: 'MØDREKVOTE' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: 'de6cb16e-9520-418c-a438-aa781b0833c2',
              eksternArbeidsforholdId: 'ARB001-002',
              arbeidsgiverReferanse: '994884174',
              utbetalingsgrad: undefined,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 15.0,
            },
          ],
          periodeResultatType: 'MANUELL_BEHANDLING',
          begrunnelse: undefined,
          periodeResultatÅrsak: '4072',
          manuellBehandlingÅrsak: '5002',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: 'FORELDREPENGER',
          utsettelseType: 'ARBEID',
          oppholdÅrsak: '-',
          mottattDato: '2023-01-05',
          gradertAktivitet: undefined,
        },
      ],
      perioderAnnenpart: [],
      årsakFilter: { kreverSammenhengendeUttakTom: '2021-09-30', utenMinsterett: false, søkerErMor: true },
      endringsdato: '2022-10-20',
    },
  },
};

export const VisAdvarselNårUtbetalingsgradOgProsentArbeidOverstiger100Prosent: Story = {
  args: {
    aksjonspunkterForPanel: åpentAksjonspunkt,
    uttaksresultat: {
      perioderSøker: [
        {
          fom: '2022-10-20',
          tom: '2022-11-09',
          aktiviteter: [
            {
              stønadskontoType: 'MØDREKVOTE' satisfies StønadskontoType,
              prosentArbeid: 51,
              arbeidsforholdId: 'de6cb16e-9520-418c-a438-aa781b0833c2',
              eksternArbeidsforholdId: 'ARB001-002',
              arbeidsgiverReferanse: '994884174',
              utbetalingsgrad: 50,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 15.0,
            },
          ],
          periodeResultatType: 'MANUELL_BEHANDLING',
          begrunnelse: undefined,
          periodeResultatÅrsak: '4072',
          manuellBehandlingÅrsak: '5002',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: 'FORELDREPENGER',
          utsettelseType: 'ARBEID',
          oppholdÅrsak: '-',
          mottattDato: '2023-01-05',
          gradertAktivitet: undefined,
        },
      ],
      perioderAnnenpart: [],
      årsakFilter: { kreverSammenhengendeUttakTom: '2021-09-30', utenMinsterett: false, søkerErMor: true },
      endringsdato: '2022-10-20',
    },
  },
};

export const VisOppholdsperiode: Story = {
  args: {
    aksjonspunkterForPanel: åpentAksjonspunkt,
    uttaksresultat: {
      perioderSøker: [
        {
          fom: '2023-02-15',
          tom: '2023-05-05',
          aktiviteter: [],
          periodeResultatType: 'INNVILGET',
          begrunnelse: undefined,
          periodeResultatÅrsak: '-',
          manuellBehandlingÅrsak: '-',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: '-',
          utsettelseType: '-',
          oppholdÅrsak: 'UTTAK_FEDREKVOTE_ANNEN_FORELDER',
          mottattDato: '2023-01-18',
          gradertAktivitet: undefined,
        },
      ],
      perioderAnnenpart: [
        {
          fom: '2023-02-03',
          tom: '2023-02-14',
          aktiviteter: [
            {
              stønadskontoType: 'FEDREKVOTE' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: undefined,
              eksternArbeidsforholdId: undefined,
              arbeidsgiverReferanse: '886998562',
              utbetalingsgrad: 100,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 8.0,
            },
            {
              stønadskontoType: 'FEDREKVOTE' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: undefined,
              eksternArbeidsforholdId: undefined,
              arbeidsgiverReferanse: '987195428',
              utbetalingsgrad: 100,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 8.0,
            },
            {
              stønadskontoType: 'FEDREKVOTE' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: undefined,
              eksternArbeidsforholdId: undefined,
              arbeidsgiverReferanse: '972315575',
              utbetalingsgrad: 100,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 8.0,
            },
          ],
          periodeResultatType: 'INNVILGET',
          begrunnelse: undefined,
          periodeResultatÅrsak: '2003',
          manuellBehandlingÅrsak: '-',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: 'FEDREKVOTE',
          utsettelseType: '-',
          oppholdÅrsak: '-',
          mottattDato: '2022-11-28',
          gradertAktivitet: undefined,
        },
        {
          fom: '2023-05-16',
          tom: '2023-05-17',
          aktiviteter: [
            {
              stønadskontoType: 'FEDREKVOTE' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: undefined,
              eksternArbeidsforholdId: undefined,
              arbeidsgiverReferanse: '987195428',
              utbetalingsgrad: 0,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 0.0,
            },
            {
              stønadskontoType: 'FEDREKVOTE' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: undefined,
              eksternArbeidsforholdId: undefined,
              arbeidsgiverReferanse: '886998562',
              utbetalingsgrad: 0,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 0.0,
            },
            {
              stønadskontoType: 'FEDREKVOTE' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: undefined,
              eksternArbeidsforholdId: undefined,
              arbeidsgiverReferanse: '972315575',
              utbetalingsgrad: 0,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 0.0,
            },
          ],
          periodeResultatType: 'AVSLÅTT',
          begrunnelse: undefined,
          periodeResultatÅrsak: '4084',
          manuellBehandlingÅrsak: '-',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: 'FEDREKVOTE',
          utsettelseType: '-',
          oppholdÅrsak: '-',
          mottattDato: '2022-11-28',
          gradertAktivitet: undefined,
        },
      ],
      årsakFilter: { kreverSammenhengendeUttakTom: '2021-09-30', utenMinsterett: true, søkerErMor: true },
      endringsdato: '2023-02-03',
    },
  },
};

export const MorPerioderI_EØSFarSamtidigUttak: Story = {
  args: {
    personoversikt: {
      bruker: {
        kjønn: 'M',
      },
    } as Personoversikt,
    fagsak: {
      relasjonsRolleType: 'FARA',
    } as Fagsak,
    uttakStonadskontoer: {
      ...uttakStonadskontoer,
      stonadskontoer: {
        ...uttakStonadskontoer.stonadskontoer,
        FELLESPERIODE: {
          stonadskontotype: 'FELLESPERIODE',
          maxDager: 80,
          saldo: 80,
          kontoReduksjoner: {
            annenForelderEøsUttak: 20,
          },
          aktivitetSaldoDtoList: [
            {
              aktivitetIdentifikator: {
                uttakArbeidType: 'ORDINÆRT_ARBEID',
                arbeidsgiverReferanse: '910909088',
              },
              saldo: 80,
            },
          ],
          gyldigForbruk: true,
        },
      },
    },
    uttaksresultat: {
      perioderSøker: [
        {
          fom: '2025-01-15',
          tom: '2025-02-04',
          aktiviteter: [
            {
              stønadskontoType: 'FEDREKVOTE' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: '7272d1a7-8dbb-4953-bb39-e0742635b2a5',
              eksternArbeidsforholdId: 'ARB001-002',
              arbeidsgiverReferanse: '994884174',
              utbetalingsgrad: 100,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 5,
            },
          ],
          periodeResultatType: 'MANUELL_BEHANDLING',
          begrunnelse: undefined,
          periodeResultatÅrsak: '4072',
          manuellBehandlingÅrsak: '5014',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: 'FELLESPERIODE',
          utsettelseType: '-',
          oppholdÅrsak: '-',
          mottattDato: '2022-12-01',
          gradertAktivitet: undefined,
        },
        {
          fom: '2025-03-25',
          tom: '2025-06-25',
          aktiviteter: [
            {
              stønadskontoType: 'FELLESPERIODE' satisfies StønadskontoType,
              prosentArbeid: 0,
              arbeidsforholdId: '7272d1a7-8dbb-4953-bb39-e0742635b2a5',
              eksternArbeidsforholdId: 'ARB001-002',
              arbeidsgiverReferanse: '994884174',
              utbetalingsgrad: 100,
              uttakArbeidType: 'ORDINÆRT_ARBEID',
              gradering: false,
              trekkdagerDesimaler: 5,
            },
          ],
          periodeResultatType: 'INNVILGET',
          begrunnelse: undefined,
          periodeResultatÅrsak: '4072',
          manuellBehandlingÅrsak: '-',
          graderingAvslagÅrsak: '-',
          flerbarnsdager: false,
          samtidigUttak: false,
          samtidigUttaksprosent: undefined,
          graderingInnvilget: false,
          periodeType: 'FELLESPERIODE',
          utsettelseType: '-',
          oppholdÅrsak: '-',
          mottattDato: '2022-12-01',
          gradertAktivitet: undefined,
        },
      ],
      perioderAnnenpart: [],
      årsakFilter: { kreverSammenhengendeUttakTom: '2021-09-30', utenMinsterett: false, søkerErMor: true },
      endringsdato: '2022-10-20',
    },
    annenForelderUttakEøs: [
      {
        fom: '2024-05-01',
        tom: '2024-12-12',
        trekkonto: 'MØDREKVOTE' satisfies StønadskontoType,
        trekkdager: 90,
      },
      {
        fom: '2025-01-15',
        tom: '2025-02-04',
        trekkonto: 'FELLESPERIODE' satisfies StønadskontoType,
        trekkdager: 20,
      },
    ],
  },
};
