import type { AksjonspunktFraBackend } from '../AksjonspunktFraBackend';

export type BekreftUttaksperioderAp = AksjonspunktFraBackend<
  | 'FAKTA_UTTAK_MANUELT_SATT_STARTDATO_ULIK_SØKNAD_STARTDATO'
  | 'FAKTA_UTTAK_INGEN_PERIODER'
  | 'FAKTA_UTTAK_GRADERING_UKJENT_AKTIVITET'
  | 'FAKTA_UTTAK_GRADERING_AKTIVITET_UTEN_BEREGNINGSGRUNNLAG'
  | 'OVERSTYRING_FAKTA_UTTAK'
>;
