name: Bygg og deploy branch manuelt
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        type: string
        required: true
      app:
        required: true
        type: choice
        description: 'Applikasjon som skal deployes fra branch'
        options:
          - fp-frontend
          - fp-avdelingsleder

jobs:
  build-app:
    name: Build
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: navikt/fp-gha-workflows/.github/workflows/build-app-frontend-yarn.yml@d82a6fe449f56938a073da20baca50bed596a800
    with:
      runs-on: 'ubuntu-latest-8-cores'
      node-version: '22.17.1'
      push-image: true
      branch: ${{ inputs.branch }}
      bake-target: ${{ inputs.app }}
      run-knip: true
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN  }}

  deploy-dev:
    name: Deploy dev
    permissions:
      id-token: write
    needs: build-app
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@d82a6fe449f56938a073da20baca50bed596a800
    with:
      gar: true
      branch: ${{ inputs.branch }}
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: dev-gcp
      image_suffix: '/${{ inputs.app }}'
      deploy_context: '/${{ inputs.app }}'
