name: Bygg og deploy branch manuelt
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        type: string
        required: true

jobs:
  build-app:
    name: Build
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: navikt/fp-gha-workflows/.github/workflows/build-app-frontend-yarn.yml@main
    with:
      runs-on: 'ubuntu-latest-8-cores'
      node-version: '22.6.0'
      push-image: true
      branch: ${{ inputs.branch }}
    secrets: inherit

  deploy-dev:
    name: Deploy dev
    permissions:
      id-token: write
    needs: build-app
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@main
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: dev-gcp
    secrets: inherit
