name: Valider pull request
on: [pull_request]
jobs:
  valid-pull-request:
    name: Valider pull request
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6.0.2

      - uses: navikt/fp-gha-workflows/.github/actions/setup-yarnrc@main
        with:
          npmAuthToken: ${{ secrets.READER_TOKEN }}

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # ratchet:actions/setup-node@v6.4.0
        with:
          node-version: 24
          cache: 'yarn'

      - name: Use turbo cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # ratchet:actions/cache@v5.0.5
        with:
          path: ~/work/fp-frontend/fp-frontend/.turbo
          key: turbo-${{ runner.os }}-${{ github.ref_name }}-${{ hashFiles('yarn.lock') }}
          restore-keys: turbo-${{ runner.os }}-master-${{ hashFiles('yarn.lock') }}

      - name: Installere dependencies
        run: yarn install --immutable

      - name: Stylelint
        run: yarn stylelint

      - name: ESLint
        run: yarn eslint

      - name: Server tests
        working-directory: server
        run: yarn install --immutable && yarn test

  knip-it:
    name: Kjør knip
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Run knip
        uses: navikt/fp-gha-workflows/.github/actions/knip-it@main
        with:
          npm-auth-token: ${{ secrets.READER_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: 'yarn'
          node-version: 24
